package org.flowcyt.cfcs;
// CFCSDatatype.java

/* ------------------------------------------------------------------------- *\
This software and documentation are provided 'as is' and Tree Star, Inc., its
contractors and partners specifically disclaim all other warranties, expressed
or implied, including but not limited to implied warranties of merchantability
and fitness for a particular purpose, or during any particular date range.

By using this software, you are agreeing to these limits of liability, and to
hold Tree Star harmless for any information, accurate or erroneous, that might
be generated by the program.  This software is intended for research use only.

Christopher Lane <cdl@best.classes> for Tree Star  1/14/2002      Copyright 2002
\* ------------------------------------------------------------------------- */


import java.io.DataOutputStream;

public interface CFCSDatatype
{

    public static final int UNDEFINED = 0;

    public static final int ASCII = 1;
    public static final int FLOAT = 2;
    public static final int DOUBLE = 3;
    public static final int BINARY = 4;

    public static final int BYTE = 1;
    public static final int SHORT = 2;
    public static final int INTEGER = 4;
    public static final int OVERSIZE = 8;

    // --------------------------------------------------------------------

    public void setSizingObject(CFCSDataSizing sizing);

    // --------------------------------------------------------------------

    public int getCount();

    // --------------------------------------------------------------------

    public void readData(int index, byte[][] table);

    public void writeData(int index, int count, DataOutputStream stream);

    // --------------------------------------------------------------------

    public void getData(int index, byte[] array) throws CFCSDataSizeError;

    public void setData(int index, byte[] array) throws CFCSDataScaleError;

    public void addData(byte[] array) throws CFCSDataScaleError;

    // --------------------------------------------------------------------

    public void getData(int index, short[] array) throws CFCSDataSizeError;

    public void setData(int index, short[] array) throws CFCSDataScaleError;

    public void addData(short[] array) throws CFCSDataScaleError;

    // --------------------------------------------------------------------

    public void getData(int index, int[] array) throws CFCSDataSizeError;

    public void setData(int index, int[] array) throws CFCSDataScaleError;

    public void addData(int[] array) throws CFCSDataScaleError;

    // --------------------------------------------------------------------

    public void getData(int index, float[] array) throws CFCSDataChannelError;

    public void setData(int index, float[] array) throws CFCSDataChannelError;

    public void addData(float[] array) throws CFCSDataChannelError;

    // --------------------------------------------------------------------

    public void getData(int index, double[] array) throws CFCSDataChannelError;

    public void setData(int index, double[] array) throws CFCSDataChannelError;

    public void addData(double[] array) throws CFCSDataChannelError;

    // --------------------------------------------------------------------

}
