package:
  name: cytoflow
  # https://www.python.org/dev/peps/pep-0440/
  version: {{ GIT_DESCRIBE_TAG if GIT_DESCRIBE_NUMBER == "0" else GIT_DESCRIBE_TAG ~ '.dev' ~ GIT_DESCRIBE_NUMBER ~ '+' ~ GIT_DESCRIBE_HASH }}

source:
  path: ../../..


build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: {{ "py38" }}
  script:
    - python setup.py build_ext --inplace
    - sphinx-build docs/user_manual/reference cytoflowgui/help
    - python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - cytoflow = cytoflowgui.run:run_gui
    - cf-channel_voltages = cytoflow.scripts.channel_voltages:main
    - cf-fcs_metadata = cytoflow.scripts.fcs_metadata:main

requirements:
  host:
    - python==3.8.5
    - numpy==1.20.2
    - pandas==1.2.5
    - matplotlib==3.3.4
    - bottleneck==1.3.2
    - numexpr==2.7.3
    - scipy==1.6.2
    - scikit-learn==0.24.2
    - seaborn==0.11.1
    - statsmodels==0.12.2
    - natsort==7.1.1

    - traits==6.2.0
    - traitsui==7.1.1
    - pyface==7.3.0
    - envisage==6.0.1
    - nbformat==5.1.3
    - python-dateutil==2.8.1
    - importlib_resources==5.2.0

    - pyqt==5.9.2
    - qt==5.9.7
    - pyopengl==3.1.1a1

    - fcsparser==0.2.1bt1
    - camel==0.1.2
    - yapf==0.30.0

    # - {{compiler('cxx')}}
    - sphinx==4.0.2
    - bleach==3.3.0
    - swig==4.0.2

  run:
    - python==3.8.5
    - numpy==1.20.2
    - pandas==1.2.5
    - matplotlib==3.3.4
    - bottleneck==1.3.2
    - numexpr==2.7.3
    - scipy==1.6.2
    - scikit-learn==0.24.2
    - seaborn==0.11.1
    - statsmodels==0.12.2
    - natsort==7.1.1

    - traits==6.2.0
    - traitsui==7.1.1
    - pyface==7.3.0
    - envisage==6.0.1
    - nbformat==5.1.3
    - python-dateutil==2.8.1
    - importlib_resources==5.2.0
    
    - pyqt==5.9.2
    - qt==5.9.7
    - pyopengl==3.1.1a1
    
    - fcsparser==0.2.1bt1
    - camel==0.1.2
    - yapf==0.30.0
    

    # make sure some compatible version of the jupyter notebook
    # gets installed
    - notebook


test:
  # Python imports
  imports:
    - cytoflow

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/cytoflow/cytoflow
  license: GPLv2
  license_file: GPL.txt
  summary: 'Quantitative analyses for flow cytometry'

app:
    own_environment: True
    entry: cytoflow
    icon: icon.png

# See
# https://conda.io/docs/building/build.html for
# more information about meta.yaml
