package:
  name: cytoflow
  # https://www.python.org/dev/peps/pep-0440/
  version: {{ GIT_DESCRIBE_TAG if GIT_DESCRIBE_NUMBER == "0" else GIT_DESCRIBE_TAG ~ '.dev' ~ GIT_DESCRIBE_NUMBER ~ '+' ~ GIT_DESCRIBE_HASH }}

source:
  path: ../../..


build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: {{ "py312" }}
  script:
    # python -c "from pip._vendor.platformdirs.windows import _pick_get_win_folder; print(_pick_get_win_folder())"
    - pip install --editable . 2>&1
    - sphinx-build docs/user_manual/reference cytoflowgui/help 2>&1
    - pip install -v -v . 2>&1
  entry_points:
    - cytoflow = cytoflowgui.run:run_gui
    - cf-channel_voltages = cytoflow.scripts.channel_voltages:main
    - cf-fcs_metadata = cytoflow.scripts.fcs_metadata:main

requirements:
  host:
    - python=3.12
    - numpy=2.2
    - pandas=2.3
    - matplotlib=3.10
    - bottleneck=1.4
    - numexpr=2.11
    - scipy=1.16
    - scikit-learn=1.7
    - seaborn=0.13.2
    - statsmodels=0.14
    - natsort=8.4
    - numba=0.61
    - opentsne=1.0.4
    - igraph=0.10
    - python-igraph=0.11
    - scikit-fda=0.10

    # version 2.2.1 of gmpy2 crashes
    - gmpy2==2.1.5

    - traits=7.0
    - traitsui=8.0
    - pyface=8.0
    - conda-forge::envisage=7.0
    - nbformat=5.10
    - python-dateutil=2.9
    - importlib_resources=6.4
    - configobj=5.0

    - defaults::qt=5.*
    - defaults::pyqt=5.*
    - defaults::pyqtwebengine=5.*

    - cytoflow::camel=0.1.2
    - yapf=0.40

    # build deps
    - setuptools>=78.1.1
    - setuptools_scm
    - pip
    - defaults::libffi
    - swig
    - anaconda-client
    - conda-build
    - conda-verify
    - sphinx
    - pandoc
    - bleach
    - pydata-sphinx-theme
    - sphinx-design

  run:
    - python=3.12
    - numpy=2.2
    - pandas=2.3
    - matplotlib=3.10
    - bottleneck=1.4
    - numexpr=2.11
    - scipy=1.16
    - scikit-learn=1.7
    - seaborn=0.13.2
    - statsmodels=0.14
    - natsort=8.4
    - numba=0.61
    - opentsne=1.0.4
    - igraph=0.10
    - python-igraph=0.11
    - scikit-fda=0.10

    # version 2.2.1 of gmpy2 crashes
    - gmpy2==2.1.5

    - traits=7.0
    - traitsui=8.0
    - pyface=8.0
    - envisage=7.0
    - nbformat=5.10
    - python-dateutil=2.9
    - importlib_resources=6.4
    - configobj=5.0

    - defaults::qt=5
    - defaults::pyqt=5
    - defaults::pyqtwebengine=5

    - cytoflow::camel=0.1.2
    - yapf=0.40

    # make sure some compatible version of the jupyterlab
    # gets installed, along with matplotlib widgets
    - ipympl
    - jupyterlab
    
    # required on windows. I have no idea why.
    - swig

test:
  # Python imports
  imports:
    - cytoflow

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/cytoflow/cytoflow
  license: GPLv2
  license_file: GPL.txt
  summary: 'Quantitative analyses for flow cytometry'
  description: |
    Python tools for quantitative, reproducible flow cytometry analysis
  dev_url: https://github.com/cytoflow/cytoflow
  doc_url: https://cytoflow.readthedocs.org

app:
    own_environment: True
    entry: cytoflow
    icon: icon.png
    summary: "Flow cytometry analysis"

