# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
   os: ubuntu-24.04
   tools:
      python: miniconda3-3.12-24.1

sphinx:
   configuration: docs/conf.py
   fail_on_warning: false

formats:
   - pdf
   - htmlzip
 
submodules:
  include: all

conda:
  environment: docs/environment-rtd.yml
