//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.08.17 at 04:08:13 PM PDT 
//


package org.flowcyt.facejava.gating.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Type of the Gating-ML element:
 * 				
 * 				At least 1 gate from the Gates group is to be specified, no upper limit, choice from the Gates group.
 * 			
 * 
 * <p>Java class for Gating-ML complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Gating-ML">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.isac-net.org/std/Gating-ML/v1.1/}Gates" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Gating-ML", propOrder = {
    "gates"
})
public class GatingML {

    @XmlElements({
        @XmlElement(name = "BooleanGate", type = BooleanGate.class),
        @XmlElement(name = "PolytopeGate", type = PolytopeGate.class),
        @XmlElement(name = "RectangleGate", type = RectangleGate.class),
        @XmlElement(name = "PolygonGate", type = PolygonGate.class),
        @XmlElement(name = "DecisionTreeGate", type = DecisionTreeGate.class),
        @XmlElement(name = "EllipsoidGate", type = EllipsoidGate.class)
    })
    protected List<AbstractGate> gates;

    /**
     * Gets the value of the gates property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gates property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGates().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BooleanGate }
     * {@link PolytopeGate }
     * {@link RectangleGate }
     * {@link PolygonGate }
     * {@link DecisionTreeGate }
     * {@link EllipsoidGate }
     * 
     * 
     */
    public List<AbstractGate> getGates() {
        if (gates == null) {
            gates = new ArrayList<AbstractGate>();
        }
        return this.gates;
    }

}
