//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.08.17 at 04:08:13 PM PDT 
//


package org.flowcyt.facejava.gating.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.flowcyt.facejava.gating.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GatingML_QNAME = new QName("http://www.isac-net.org/std/Gating-ML/v1.1/", "Gating-ML");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.flowcyt.facejava.gating.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GateReference }
     * 
     */
    public GateReference createGateReference() {
        return new GateReference();
    }

    /**
     * Create an instance of {@link DecisionTreeGate }
     * 
     */
    public DecisionTreeGate createDecisionTreeGate() {
        return new DecisionTreeGate();
    }

    /**
     * Create an instance of {@link TwoAndMoreOperandsBoolGate }
     * 
     */
    public TwoAndMoreOperandsBoolGate createTwoAndMoreOperandsBoolGate() {
        return new TwoAndMoreOperandsBoolGate();
    }

    /**
     * Create an instance of {@link LeafNode }
     * 
     */
    public LeafNode createLeafNode() {
        return new LeafNode();
    }

    /**
     * Create an instance of {@link BooleanGate }
     * 
     */
    public BooleanGate createBooleanGate() {
        return new BooleanGate();
    }

    /**
     * Create an instance of {@link OneOperandBoolGate }
     * 
     */
    public OneOperandBoolGate createOneOperandBoolGate() {
        return new OneOperandBoolGate();
    }

    /**
     * Create an instance of {@link PolygonGate }
     * 
     */
    public PolygonGate createPolygonGate() {
        return new PolygonGate();
    }

    /**
     * Create an instance of {@link Dimension }
     * 
     */
    public Dimension createDimension() {
        return new Dimension();
    }

    /**
     * Create an instance of {@link EllipsoidGate }
     * 
     */
    public EllipsoidGate createEllipsoidGate() {
        return new EllipsoidGate();
    }

    /**
     * Create an instance of {@link Coordinate }
     * 
     */
    public Coordinate createCoordinate() {
        return new Coordinate();
    }

    /**
     * Create an instance of {@link Point2D }
     * 
     */
    public Point2D createPoint2D() {
        return new Point2D();
    }

    /**
     * Create an instance of {@link PolytopeGate }
     * 
     */
    public PolytopeGate createPolytopeGate() {
        return new PolytopeGate();
    }

    /**
     * Create an instance of {@link Point }
     * 
     */
    public Point createPoint() {
        return new Point();
    }

    /**
     * Create an instance of {@link GatingML }
     * 
     */
    public GatingML createGatingML() {
        return new GatingML();
    }

    /**
     * Create an instance of {@link TreeNode }
     * 
     */
    public TreeNode createTreeNode() {
        return new TreeNode();
    }

    /**
     * Create an instance of {@link RectangleGate }
     * 
     */
    public RectangleGate createRectangleGate() {
        return new RectangleGate();
    }

    /**
     * Create an instance of {@link RectangleGateDimension }
     * 
     */
    public RectangleGateDimension createRectangleGateDimension() {
        return new RectangleGateDimension();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GatingML }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.isac-net.org/std/Gating-ML/v1.1/", name = "Gating-ML")
    public JAXBElement<GatingML> createGatingML(GatingML value) {
        return new JAXBElement<GatingML>(_GatingML_QNAME, GatingML.class, null, value);
    }

}
