//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.08.17 at 04:08:13 PM PDT 
//


package org.flowcyt.facejava.gating.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Boolean Gates with exactly one operand (NOT gate).	
 * 			
 * 
 * <p>Java class for OneOperand-BoolGate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OneOperand-BoolGate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.isac-net.org/std/Gating-ML/v1.1/}BoolGateOperands"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OneOperand-BoolGate", propOrder = {
    "gateReference",
    "rectangleGate",
    "polygonGate",
    "polytopeGate",
    "ellipsoidGate",
    "booleanGate",
    "decisionTreeGate"
})
public class OneOperandBoolGate {

    protected GateReference gateReference;
    @XmlElement(name = "RectangleGate")
    protected RectangleGate rectangleGate;
    @XmlElement(name = "PolygonGate")
    protected PolygonGate polygonGate;
    @XmlElement(name = "PolytopeGate")
    protected PolytopeGate polytopeGate;
    @XmlElement(name = "EllipsoidGate")
    protected EllipsoidGate ellipsoidGate;
    @XmlElement(name = "BooleanGate")
    protected BooleanGate booleanGate;
    @XmlElement(name = "DecisionTreeGate")
    protected DecisionTreeGate decisionTreeGate;

    /**
     * Gets the value of the gateReference property.
     * 
     * @return
     *     possible object is
     *     {@link GateReference }
     *     
     */
    public GateReference getGateReference() {
        return gateReference;
    }

    /**
     * Sets the value of the gateReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link GateReference }
     *     
     */
    public void setGateReference(GateReference value) {
        this.gateReference = value;
    }

    /**
     * Gets the value of the rectangleGate property.
     * 
     * @return
     *     possible object is
     *     {@link RectangleGate }
     *     
     */
    public RectangleGate getRectangleGate() {
        return rectangleGate;
    }

    /**
     * Sets the value of the rectangleGate property.
     * 
     * @param value
     *     allowed object is
     *     {@link RectangleGate }
     *     
     */
    public void setRectangleGate(RectangleGate value) {
        this.rectangleGate = value;
    }

    /**
     * Gets the value of the polygonGate property.
     * 
     * @return
     *     possible object is
     *     {@link PolygonGate }
     *     
     */
    public PolygonGate getPolygonGate() {
        return polygonGate;
    }

    /**
     * Sets the value of the polygonGate property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolygonGate }
     *     
     */
    public void setPolygonGate(PolygonGate value) {
        this.polygonGate = value;
    }

    /**
     * Gets the value of the polytopeGate property.
     * 
     * @return
     *     possible object is
     *     {@link PolytopeGate }
     *     
     */
    public PolytopeGate getPolytopeGate() {
        return polytopeGate;
    }

    /**
     * Sets the value of the polytopeGate property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolytopeGate }
     *     
     */
    public void setPolytopeGate(PolytopeGate value) {
        this.polytopeGate = value;
    }

    /**
     * Gets the value of the ellipsoidGate property.
     * 
     * @return
     *     possible object is
     *     {@link EllipsoidGate }
     *     
     */
    public EllipsoidGate getEllipsoidGate() {
        return ellipsoidGate;
    }

    /**
     * Sets the value of the ellipsoidGate property.
     * 
     * @param value
     *     allowed object is
     *     {@link EllipsoidGate }
     *     
     */
    public void setEllipsoidGate(EllipsoidGate value) {
        this.ellipsoidGate = value;
    }

    /**
     * Gets the value of the booleanGate property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanGate }
     *     
     */
    public BooleanGate getBooleanGate() {
        return booleanGate;
    }

    /**
     * Sets the value of the booleanGate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanGate }
     *     
     */
    public void setBooleanGate(BooleanGate value) {
        this.booleanGate = value;
    }

    /**
     * Gets the value of the decisionTreeGate property.
     * 
     * @return
     *     possible object is
     *     {@link DecisionTreeGate }
     *     
     */
    public DecisionTreeGate getDecisionTreeGate() {
        return decisionTreeGate;
    }

    /**
     * Sets the value of the decisionTreeGate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DecisionTreeGate }
     *     
     */
    public void setDecisionTreeGate(DecisionTreeGate value) {
        this.decisionTreeGate = value;
    }

}
