//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.08.17 at 04:08:13 PM PDT 
//


package org.flowcyt.facejava.gating.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Type of the RectangleGate element:
 * 				
 * 				Each parameter of a rectangular gate shall be described by one dimension element 
 * 				(subelement of the RectangleGate element). 
 * 				The maximum number of dimension elements is unbounded. Each dimension specifies 
 * 				range in the specified FCS parameter (parameter attribute) between the min and max values 
 * 				(specified by min and max attributes). 
 * 				
 * 				If the max attribute is absent, then the range in this parameter is considered as (min, unlimited). 
 * 				If the min attribute is absent, then the range in this parameter is considered as (-unlimited, max). 
 * 				
 * 				The min and max attributes are double numbers.
 * 				
 * 				Parameters may be transformed
 * 				The boundary is considered as MinInclusive-MaxExclusive
 * 				
 * 				"Range Gates": just one dimension element
 * 				"Rectangular Gates": two dimension elements
 * 				"Hyper-rectangular Gates": more than two dimension elements 
 * 			
 * 
 * <p>Java class for RectangleGate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RectangleGate">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.isac-net.org/std/Gating-ML/v1.1/}AbstractGate">
 *       &lt;sequence>
 *         &lt;element name="dimension" type="{http://www.isac-net.org/std/Gating-ML/v1.1/}RectangleGateDimension" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RectangleGate", propOrder = {
    "dimension"
})
public class RectangleGate
    extends AbstractGate
{

    @XmlElement(required = true)
    protected List<RectangleGateDimension> dimension;

    /**
     * Gets the value of the dimension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dimension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDimension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RectangleGateDimension }
     * 
     * 
     */
    public List<RectangleGateDimension> getDimension() {
        if (dimension == null) {
            dimension = new ArrayList<RectangleGateDimension>();
        }
        return this.dimension;
    }

}
