//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.08.17 at 04:08:13 PM PDT 
//


package org.flowcyt.facejava.gating.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				For a given event the channel value of the specified parameter is compared against the threshold. If it is less than 
 * 				the threshold, then the decision is passed to the “Less Than” branch; if the value is greater or equal to the threshold, 
 * 				then the decision is passed to the “Greater Than or Equal” branch. 
 * 				
 * 				Both the “Less Than” and the “Greater Than or Equal” nodes may be either a non-terminal node 
 * 				or a terminal leaf. In case it is a non-terminal node the computation continues. In case it is a terminal leaf node 
 * 				the decision is made according the inside attribute of the "leaf" element. 
 * 			
 * 
 * <p>Java class for TreeNode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TreeNode">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.isac-net.org/std/Gating-ML/v1.1/}LessThan-TreeBranch"/>
 *         &lt;group ref="{http://www.isac-net.org/std/Gating-ML/v1.1/}GreaterThanOrEqual-TreeBranch"/>
 *       &lt;/sequence>
 *       &lt;attribute name="parameter" use="required" type="{http://www.isac-net.org/std/common-types/v1.0/}NonEmptyString" />
 *       &lt;attribute name="threshold" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TreeNode", propOrder = {
    "nodeLT",
    "leafLT",
    "nodeGTE",
    "leafGTE"
})
public class TreeNode {

    protected TreeNode nodeLT;
    protected LeafNode leafLT;
    protected TreeNode nodeGTE;
    protected LeafNode leafGTE;
    @XmlAttribute(namespace = "http://www.isac-net.org/std/Gating-ML/v1.1/", required = true)
    protected String parameter;
    @XmlAttribute(namespace = "http://www.isac-net.org/std/Gating-ML/v1.1/", required = true)
    protected double threshold;

    /**
     * Gets the value of the nodeLT property.
     * 
     * @return
     *     possible object is
     *     {@link TreeNode }
     *     
     */
    public TreeNode getNodeLT() {
        return nodeLT;
    }

    /**
     * Sets the value of the nodeLT property.
     * 
     * @param value
     *     allowed object is
     *     {@link TreeNode }
     *     
     */
    public void setNodeLT(TreeNode value) {
        this.nodeLT = value;
    }

    /**
     * Gets the value of the leafLT property.
     * 
     * @return
     *     possible object is
     *     {@link LeafNode }
     *     
     */
    public LeafNode getLeafLT() {
        return leafLT;
    }

    /**
     * Sets the value of the leafLT property.
     * 
     * @param value
     *     allowed object is
     *     {@link LeafNode }
     *     
     */
    public void setLeafLT(LeafNode value) {
        this.leafLT = value;
    }

    /**
     * Gets the value of the nodeGTE property.
     * 
     * @return
     *     possible object is
     *     {@link TreeNode }
     *     
     */
    public TreeNode getNodeGTE() {
        return nodeGTE;
    }

    /**
     * Sets the value of the nodeGTE property.
     * 
     * @param value
     *     allowed object is
     *     {@link TreeNode }
     *     
     */
    public void setNodeGTE(TreeNode value) {
        this.nodeGTE = value;
    }

    /**
     * Gets the value of the leafGTE property.
     * 
     * @return
     *     possible object is
     *     {@link LeafNode }
     *     
     */
    public LeafNode getLeafGTE() {
        return leafGTE;
    }

    /**
     * Sets the value of the leafGTE property.
     * 
     * @param value
     *     allowed object is
     *     {@link LeafNode }
     *     
     */
    public void setLeafGTE(LeafNode value) {
        this.leafGTE = value;
    }

    /**
     * Gets the value of the parameter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParameter() {
        return parameter;
    }

    /**
     * Sets the value of the parameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParameter(String value) {
        this.parameter = value;
    }

    /**
     * Gets the value of the threshold property.
     * 
     */
    public double getThreshold() {
        return threshold;
    }

    /**
     * Sets the value of the threshold property.
     * 
     */
    public void setThreshold(double value) {
        this.threshold = value;
    }

}
