//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.08.17 at 04:08:13 PM PDT 
//


package org.flowcyt.facejava.gating.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Boolean Gates with two or more parameters (AND and OR gates).
 * 			
 * 
 * <p>Java class for TwoAndMoreOperands-BoolGate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TwoAndMoreOperands-BoolGate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="2">
 *         &lt;group ref="{http://www.isac-net.org/std/Gating-ML/v1.1/}BoolGateOperands"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TwoAndMoreOperands-BoolGate", propOrder = {
    "gateReferenceOrRectangleGateOrPolygonGate"
})
public class TwoAndMoreOperandsBoolGate {

    @XmlElements({
        @XmlElement(name = "DecisionTreeGate", type = DecisionTreeGate.class),
        @XmlElement(name = "RectangleGate", type = RectangleGate.class),
        @XmlElement(name = "PolygonGate", type = PolygonGate.class),
        @XmlElement(name = "gateReference", type = GateReference.class),
        @XmlElement(name = "EllipsoidGate", type = EllipsoidGate.class),
        @XmlElement(name = "BooleanGate", type = BooleanGate.class),
        @XmlElement(name = "PolytopeGate", type = PolytopeGate.class)
    })
    protected List<Object> gateReferenceOrRectangleGateOrPolygonGate;

    /**
     * Gets the value of the gateReferenceOrRectangleGateOrPolygonGate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gateReferenceOrRectangleGateOrPolygonGate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGateReferenceOrRectangleGateOrPolygonGate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DecisionTreeGate }
     * {@link RectangleGate }
     * {@link PolygonGate }
     * {@link GateReference }
     * {@link EllipsoidGate }
     * {@link BooleanGate }
     * {@link PolytopeGate }
     * 
     * 
     */
    public List<Object> getGateReferenceOrRectangleGateOrPolygonGate() {
        if (gateReferenceOrRectangleGateOrPolygonGate == null) {
            gateReferenceOrRectangleGateOrPolygonGate = new ArrayList<Object>();
        }
        return this.gateReferenceOrRectangleGateOrPolygonGate;
    }

}
