from PyInstaller.utils.hooks import copy_metadata
datas = copy_metadata('traitsui')

# collect_submodules tries to import traitsui.qt, which obviously doesn't
# work on headless linux. so, specify all the submodules here instead.

hiddenimports = ['traitsui.qt', 
                 'traitsui.qt.rgb_color_trait', 
                 'traitsui.qt.date_range_editor', 
                 'traitsui.qt.extra.progress_renderer', 
                 'traitsui.qt.title_editor', 
                 'traitsui.qt.boolean_editor', 
                 'traitsui.qt.extra.bounds_editor', 
                 'traitsui.qt.color_editor', 
                 'traitsui.qt.drop_editor', 
                 'traitsui.qt.ui_panel', 
                 'traitsui.qt.array_editor', 
                 'traitsui.qt.font_trait', 
                 'traitsui.qt.array_view_editor', 
                 'traitsui.qt.extra.qt_view', 
                 'traitsui.qt.text_editor', 
                 'traitsui.qt.key_event_to_name', 
                 'traitsui.qt.extra', 
                 'traitsui.qt.tests.test_helper',
                 'traitsui.qt.helper', 
                 'traitsui.qt.extra.range_slider', 
                 'traitsui.qt.enum_editor', 
                 'traitsui.qt.ui_modal', 
                 'traitsui.qt.value_editor', 
                 'traitsui.qt.directory_editor', 
                 'traitsui.qt.video_editor', 
                 'traitsui.qt.list_str_editor', 
                 'traitsui.qt.styled_date_editor', 
                 'traitsui.qt.table_editor', 
                 'traitsui.qt.tuple_editor', 
                 'traitsui.qt.color_trait', 
                 'traitsui.qt.ui_base', 
                 'traitsui.qt.check_list_editor', 
                 'traitsui.qt.file_editor', 
                 'traitsui.qt.search_editor', 
                 'traitsui.qt.ui_editor', 
                 'traitsui.qt.key_binding_editor', 
                 'traitsui.qt.extra.led_editor', 
                 'traitsui.qt.instance_editor', 
                 'traitsui.qt.tests.test_tabular_model', 
                 'traitsui.qt.view_application', 
                 'traitsui.qt.editor', 
                 'traitsui.qt.tabular_editor', 
                 'traitsui.qt.extra.table_image_renderer', 
                 'traitsui.qt.menu', 
                 'traitsui.qt.tree_editor', 
                 'traitsui.qt.shell_editor', 
                 'traitsui.qt.ui_live', 
                 'traitsui.qt.table_model', 
                 'traitsui.qt.null_editor', 
                 'traitsui.qt.data_frame_editor', 
                 'traitsui.qt.list_str_model', 
                 'traitsui.qt.image_editor', 
                 'traitsui.qt.code_editor', 
                 'traitsui.qt.time_editor', 
                 'traitsui.qt.tabular_model', 
                 'traitsui.qt.image_enum_editor', 
                 'traitsui.qt.editor_factory', 
                 'traitsui.qt.tests.test_ui_panel', 
                 'traitsui.qt.extra.checkbox_renderer', 
                 'traitsui.qt.set_editor', 
                 'traitsui.qt.custom_editor', 
                 'traitsui.qt.font_editor', 
                 'traitsui.qt.csv_list_editor', 
                 'traitsui.qt.html_editor', 
                 'traitsui.qt.tests.test_ui_base', 
                 'traitsui.qt.compound_editor', 
                 'traitsui.qt.button_editor', 
                 'traitsui.qt.clipboard', 
                 'traitsui.qt.toolkit', 
                 'traitsui.qt.constants', 
                 'traitsui.qt.date_editor', 
                 'traitsui.qt.history_editor', 
                 'traitsui.qt.progress_editor', 
                 'traitsui.qt.datetime_editor', 
                 'traitsui.qt.range_editor',
                 'traitsui.qt.list_editor', 
                 'traitsui.qt.tree_node_renderers', 
                 'traitsui.qt.rgb_color_editor', 
                 'traitsui.qt.tests']







