from PyInstaller.utils.hooks import copy_metadata
datas = copy_metadata('traitsui')

# collect_submodules tries to import traitsui.qt4, which obviously doesn't
# work on headless linux. so, specify all the submodules here instead.

hiddenimports = ['traitsui.qt4', 
                 'traitsui.qt4.rgb_color_trait', 
                 'traitsui.qt4.date_range_editor', 
                 'traitsui.qt4.extra.progress_renderer', 
                 'traitsui.qt4.title_editor', 
                 'traitsui.qt4.boolean_editor', 
                 'traitsui.qt4.extra.bounds_editor', 
                 'traitsui.qt4.color_editor', 
                 'traitsui.qt4.drop_editor', 
                 'traitsui.qt4.ui_panel', 
                 'traitsui.qt4.array_editor', 
                 'traitsui.qt4.font_trait', 
                 'traitsui.qt4.array_view_editor', 
                 'traitsui.qt4.extra.qt_view', 
                 'traitsui.qt4.text_editor', 
                 'traitsui.qt4.key_event_to_name', 
                 'traitsui.qt4.extra', 
                 'traitsui.qt4.tests.test_helper',
                 'traitsui.qt4.helper', 
                 'traitsui.qt4.extra.range_slider', 
                 'traitsui.qt4.enum_editor', 
                 'traitsui.qt4.ui_modal', 
                 'traitsui.qt4.value_editor', 
                 'traitsui.qt4.directory_editor', 
                 'traitsui.qt4.video_editor', 
                 'traitsui.qt4.list_str_editor', 
                 'traitsui.qt4.styled_date_editor', 
                 'traitsui.qt4.table_editor', 
                 'traitsui.qt4.tuple_editor', 
                 'traitsui.qt4.color_trait', 
                 'traitsui.qt4.ui_base', 
                 'traitsui.qt4.check_list_editor', 
                 'traitsui.qt4.file_editor', 
                 'traitsui.qt4.search_editor', 
                 'traitsui.qt4.ui_editor', 
                 'traitsui.qt4.key_binding_editor', 
                 'traitsui.qt4.extra.led_editor', 
                 'traitsui.qt4.instance_editor', 
                 'traitsui.qt4.tests.test_tabular_model', 
                 'traitsui.qt4.view_application', 
                 'traitsui.qt4.editor', 
                 'traitsui.qt4.tabular_editor', 
                 'traitsui.qt4.extra.table_image_renderer', 
                 'traitsui.qt4.menu', 
                 'traitsui.qt4.tree_editor', 
                 'traitsui.qt4.shell_editor', 
                 'traitsui.qt4.ui_live', 
                 'traitsui.qt4.table_model', 
                 'traitsui.qt4.null_editor', 
                 'traitsui.qt4.data_frame_editor', 
                 'traitsui.qt4.list_str_model', 
                 'traitsui.qt4.image_editor', 
                 'traitsui.qt4.code_editor', 
                 'traitsui.qt4.time_editor', 
                 'traitsui.qt4.tabular_model', 
                 'traitsui.qt4.image_enum_editor', 
                 'traitsui.qt4.editor_factory', 
                 'traitsui.qt4.tests.test_ui_panel', 
                 'traitsui.qt4.extra.checkbox_renderer', 
                 'traitsui.qt4.set_editor', 
                 'traitsui.qt4.custom_editor', 
                 'traitsui.qt4.font_editor', 
                 'traitsui.qt4.csv_list_editor', 
                 'traitsui.qt4.html_editor', 
                 'traitsui.qt4.tests.test_ui_base', 
                 'traitsui.qt4.compound_editor', 
                 'traitsui.qt4.button_editor', 
                 'traitsui.qt4.clipboard', 
                 'traitsui.qt4.toolkit', 
                 'traitsui.qt4.constants', 
                 'traitsui.qt4.date_editor', 
                 'traitsui.qt4.history_editor', 
                 'traitsui.qt4.progress_editor', 
                 'traitsui.qt4.datetime_editor', 
                 'traitsui.qt4.range_editor',
                 'traitsui.qt4.list_editor', 
                 'traitsui.qt4.tree_node_renderers', 
                 'traitsui.qt4.rgb_color_editor', 
                 'traitsui.qt4.tests']







