//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.08.17 at 04:09:29 PM PDT 
//


package org.flowcyt.facejava.transformation.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				HyperLog (HL) transformation as described in:
 * 				- Bagwell, C.B., Hyperlog-a flexible log-like transform for negative, zero, and positive valued data. 
 * 				Cytometry A, 2005. 64(1): p. 34-42. http://www3.interscience.wiley.com/cgi-bin/abstract/109921021/ABSTRACT
 * 				
 * 				HL(parameter) = root(EH(y,b) - parameter), where
 * 				- if(y greater or equal 0) then EH(y,b,d,r) = 10^{yd/r}+by*d/r-1
 * 				- if(y less than 0) then EH(y,b,d,r) =-10^{-yd/r}+by*d/r+1
 * 				
 * 				the constants r and d are inherited from the Abstract-r-d-Transformation type
 * 			
 * 
 * <p>Java class for Hyperlog complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Hyperlog">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.isac-net.org/std/Transformation-ML/v1.0/}Abstract-r-d-Transformation">
 *       &lt;attribute name="b" use="required" type="{http://www.isac-net.org/std/common-types/v1.0/}PositiveDouble" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Hyperlog", namespace = "http://www.isac-net.org/std/Transformation-ML/v1.0/")
public class Hyperlog
    extends AbstractRDTransformation
{

    @XmlAttribute(namespace = "http://www.isac-net.org/std/Transformation-ML/v1.0/", required = true)
    protected double b;

    /**
     * Gets the value of the b property.
     * 
     */
    public double getB() {
        return b;
    }

    /**
     * Sets the value of the b property.
     * 
     */
    public void setB(double value) {
        this.b = value;
    }

}
