//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.08.17 at 04:09:29 PM PDT 
//


package org.flowcyt.facejava.transformation.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Natural log transformation: 
 * 				
 * 				for parameter greater than or equal 1: 
 * 					new parameter = ln(parameter) * r/d 
 * 				for parameter les than 1: 
 * 					new parameter = 0
 * 					
 * 				the constants r and d are inherited from the Abstract-r-d-Transformation type
 * 				the base of the logarithm is e = 2.71828 18284 59045 23536 02874 7135... 			
 * 			
 * 
 * <p>Java class for Ln complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Ln">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.isac-net.org/std/Transformation-ML/v1.0/}Abstract-r-d-Transformation">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Ln", namespace = "http://www.isac-net.org/std/Transformation-ML/v1.0/")
public class Ln
    extends AbstractRDTransformation
{


}
