//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.08.17 at 04:09:29 PM PDT 
//


package org.flowcyt.facejava.transformation.jaxb;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * <p>Java class for otherwise.type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="otherwise.type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{http://www.w3.org/1998/Math/MathML}otherwise.content"/>
 *       &lt;attGroup ref="{http://www.w3.org/1998/Math/MathML}Common.attrib"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "otherwise.type", propOrder = {
    "cn",
    "ci",
    "csymbol",
    "abs",
    "conjugate",
    "factorial",
    "arg",
    "real",
    "imaginary",
    "floor",
    "ceiling",
    "quotient",
    "divide",
    "rem",
    "minus",
    "plus",
    "times",
    "power",
    "root",
    "max",
    "min",
    "gcd",
    "lcm",
    "sum",
    "product",
    "compose",
    "domain",
    "codomain",
    "image",
    "domainofapplication",
    "ident",
    "and",
    "or",
    "xor",
    "not",
    "exists",
    "forall",
    "implies",
    "naturalnumbers",
    "primes",
    "integers",
    "rationals",
    "reals",
    "complexes",
    "emptyset",
    "exponentiale",
    "imaginaryi",
    "pi",
    "eulergamma",
    "_true",
    "_false",
    "infinity",
    "notanumber",
    "set",
    "list",
    "union",
    "intersect",
    "in",
    "notin",
    "subset",
    "prsubset",
    "notsubset",
    "notprsubset",
    "setdiff",
    "card",
    "cartesianproduct",
    "eq",
    "neq",
    "leq",
    "lt",
    "geq",
    "gt",
    "equivalent",
    "approx",
    "factorof",
    "exp",
    "ln",
    "log",
    "logbase",
    "sin",
    "cos",
    "tan",
    "sec",
    "csc",
    "cot",
    "arcsin",
    "arccos",
    "arctan",
    "arcsec",
    "arccsc",
    "arccot",
    "sinh",
    "cosh",
    "tanh",
    "sech",
    "csch",
    "coth",
    "arccosh",
    "arccoth",
    "arccsch",
    "arcsech",
    "arcsinh",
    "arctanh",
    "_int",
    "diff",
    "partialdiff",
    "limit",
    "lowlimit",
    "uplimit",
    "tendsto",
    "vector",
    "matrix",
    "determinant",
    "transpose",
    "selector",
    "vectorproduct",
    "scalarproduct",
    "outerproduct",
    "divergence",
    "grad",
    "curl",
    "laplacian",
    "mean",
    "sdev",
    "variance",
    "median",
    "mode",
    "moment",
    "momentabout",
    "apply",
    "interval",
    "inverse",
    "condition",
    "declare",
    "lambda",
    "piecewise",
    "bvar",
    "degree",
    "semantics",
    "mi",
    "mo",
    "mn",
    "mtext",
    "ms",
    "mrow",
    "mfrac",
    "msqrt",
    "mroot",
    "mpadded",
    "mphantom",
    "mfenced",
    "menclose",
    "msub",
    "msup",
    "msubsup",
    "munder",
    "mover",
    "munderover",
    "mmultiscripts",
    "mtable",
    "maligngroup",
    "malignmark",
    "mspace",
    "maction",
    "merror",
    "mstyle"
})
public class OtherwiseType {

    protected CnType cn;
    protected CiType ci;
    protected CsymbolType csymbol;
    protected ArithType abs;
    protected ArithType conjugate;
    protected ArithType factorial;
    protected ArithType arg;
    protected ArithType real;
    protected ArithType imaginary;
    protected ArithType floor;
    protected ArithType ceiling;
    protected ArithType quotient;
    protected ArithType divide;
    protected ArithType rem;
    protected ArithType minus;
    protected ArithType plus;
    protected ArithType times;
    protected ArithType power;
    protected ArithType root;
    protected ArithType max;
    protected ArithType min;
    protected ArithType gcd;
    protected ArithType lcm;
    protected ArithType sum;
    protected ArithType product;
    protected FunctionsType compose;
    protected FunctionsType domain;
    protected FunctionsType codomain;
    protected FunctionsType image;
    protected DomainofapplicationType domainofapplication;
    protected FunctionsType ident;
    protected ElementaryFunctionsType and;
    protected LogicType or;
    protected LogicType xor;
    protected LogicType not;
    protected LogicType exists;
    protected LogicType forall;
    protected LogicType implies;
    protected ConstantType naturalnumbers;
    protected ConstantType primes;
    protected ConstantType integers;
    protected ConstantType rationals;
    protected ConstantType reals;
    protected ConstantType complexes;
    protected ConstantType emptyset;
    protected ConstantType exponentiale;
    protected ConstantType imaginaryi;
    protected ConstantType pi;
    protected ConstantType eulergamma;
    @XmlElement(name = "true")
    protected ConstantType _true;
    @XmlElement(name = "false")
    protected ConstantType _false;
    protected ConstantType infinity;
    protected ConstantType notanumber;
    protected SetType set;
    protected ListType list;
    protected UnionType union;
    protected IntersectType intersect;
    protected InType in;
    protected NotinType notin;
    protected SubsetType subset;
    protected PrsubsetType prsubset;
    protected NotsubsetType notsubset;
    protected NotprsubsetType notprsubset;
    protected SetdiffType setdiff;
    protected CardType card;
    protected CartesianproductType cartesianproduct;
    protected RelationsType eq;
    protected RelationsType neq;
    protected RelationsType leq;
    protected RelationsType lt;
    protected RelationsType geq;
    protected RelationsType gt;
    protected RelationsType equivalent;
    protected RelationsType approx;
    protected RelationsType factorof;
    protected ElementaryFunctionsType exp;
    protected ElementaryFunctionsType ln;
    protected ElementaryFunctionsType log;
    protected LogbaseType logbase;
    protected ElementaryFunctionsType sin;
    protected ElementaryFunctionsType cos;
    protected ElementaryFunctionsType tan;
    protected ElementaryFunctionsType sec;
    protected ElementaryFunctionsType csc;
    protected ElementaryFunctionsType cot;
    protected ElementaryFunctionsType arcsin;
    protected ElementaryFunctionsType arccos;
    protected ElementaryFunctionsType arctan;
    protected ElementaryFunctionsType arcsec;
    protected ElementaryFunctionsType arccsc;
    protected ElementaryFunctionsType arccot;
    protected ElementaryFunctionsType sinh;
    protected ElementaryFunctionsType cosh;
    protected ElementaryFunctionsType tanh;
    protected ElementaryFunctionsType sech;
    protected ElementaryFunctionsType csch;
    protected ElementaryFunctionsType coth;
    protected ElementaryFunctionsType arccosh;
    protected ElementaryFunctionsType arccoth;
    protected ElementaryFunctionsType arccsch;
    protected ElementaryFunctionsType arcsech;
    protected ElementaryFunctionsType arcsinh;
    protected ElementaryFunctionsType arctanh;
    @XmlElement(name = "int")
    protected IntType _int;
    protected DiffType diff;
    protected PartialdiffType partialdiff;
    protected LimitType limit;
    protected LowlimitType lowlimit;
    protected UplimitType uplimit;
    protected TendstoType tendsto;
    protected VectorType vector;
    protected MatrixType matrix;
    protected DeterminantType determinant;
    protected TransposeType transpose;
    protected SelectorType selector;
    protected VectorproductType vectorproduct;
    protected ScalarproductType scalarproduct;
    protected OuterproductType outerproduct;
    protected DivergenceType divergence;
    protected GradType grad;
    protected CurlType curl;
    protected LaplacianType laplacian;
    protected MeanType mean;
    protected SdevType sdev;
    protected VarianceType variance;
    protected MedianType median;
    protected ModeType mode;
    protected MomentType moment;
    protected MomentaboutType momentabout;
    protected ApplyType apply;
    protected IntervalType interval;
    protected InverseType inverse;
    protected ConditionType condition;
    protected DeclareType declare;
    protected LambdaType lambda;
    protected PiecewiseType piecewise;
    protected BvarType bvar;
    protected DegreeType degree;
    protected SemanticsType semantics;
    protected MiType mi;
    protected MoType mo;
    protected MnType mn;
    protected MtextType mtext;
    protected MsType ms;
    protected MrowType mrow;
    protected MfracType mfrac;
    protected MsqrtType msqrt;
    protected MrootType mroot;
    protected MpaddedType mpadded;
    protected MphantomType mphantom;
    protected MfencedType mfenced;
    protected MencloseType menclose;
    protected MsubType msub;
    protected MsupType msup;
    protected MsubsupType msubsup;
    protected MunderType munder;
    protected MoverType mover;
    protected MunderoverType munderover;
    protected MmultiscriptsType mmultiscripts;
    protected MtableType mtable;
    protected MaligngroupType maligngroup;
    protected MalignmarkType malignmark;
    protected MspaceType mspace;
    protected MactionType maction;
    protected MerrorType merror;
    protected MstyleType mstyle;
    @XmlAttribute(name = "class")
    protected List<String> clazz;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute
    protected String style;
    @XmlAttribute
    @XmlIDREF
    protected Object xref;
    @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
    protected String href;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the cn property.
     * 
     * @return
     *     possible object is
     *     {@link CnType }
     *     
     */
    public CnType getCn() {
        return cn;
    }

    /**
     * Sets the value of the cn property.
     * 
     * @param value
     *     allowed object is
     *     {@link CnType }
     *     
     */
    public void setCn(CnType value) {
        this.cn = value;
    }

    /**
     * Gets the value of the ci property.
     * 
     * @return
     *     possible object is
     *     {@link CiType }
     *     
     */
    public CiType getCi() {
        return ci;
    }

    /**
     * Sets the value of the ci property.
     * 
     * @param value
     *     allowed object is
     *     {@link CiType }
     *     
     */
    public void setCi(CiType value) {
        this.ci = value;
    }

    /**
     * Gets the value of the csymbol property.
     * 
     * @return
     *     possible object is
     *     {@link CsymbolType }
     *     
     */
    public CsymbolType getCsymbol() {
        return csymbol;
    }

    /**
     * Sets the value of the csymbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link CsymbolType }
     *     
     */
    public void setCsymbol(CsymbolType value) {
        this.csymbol = value;
    }

    /**
     * Gets the value of the abs property.
     * 
     * @return
     *     possible object is
     *     {@link ArithType }
     *     
     */
    public ArithType getAbs() {
        return abs;
    }

    /**
     * Sets the value of the abs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArithType }
     *     
     */
    public void setAbs(ArithType value) {
        this.abs = value;
    }

    /**
     * Gets the value of the conjugate property.
     * 
     * @return
     *     possible object is
     *     {@link ArithType }
     *     
     */
    public ArithType getConjugate() {
        return conjugate;
    }

    /**
     * Sets the value of the conjugate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArithType }
     *     
     */
    public void setConjugate(ArithType value) {
        this.conjugate = value;
    }

    /**
     * Gets the value of the factorial property.
     * 
     * @return
     *     possible object is
     *     {@link ArithType }
     *     
     */
    public ArithType getFactorial() {
        return factorial;
    }

    /**
     * Sets the value of the factorial property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArithType }
     *     
     */
    public void setFactorial(ArithType value) {
        this.factorial = value;
    }

    /**
     * Gets the value of the arg property.
     * 
     * @return
     *     possible object is
     *     {@link ArithType }
     *     
     */
    public ArithType getArg() {
        return arg;
    }

    /**
     * Sets the value of the arg property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArithType }
     *     
     */
    public void setArg(ArithType value) {
        this.arg = value;
    }

    /**
     * Gets the value of the real property.
     * 
     * @return
     *     possible object is
     *     {@link ArithType }
     *     
     */
    public ArithType getReal() {
        return real;
    }

    /**
     * Sets the value of the real property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArithType }
     *     
     */
    public void setReal(ArithType value) {
        this.real = value;
    }

    /**
     * Gets the value of the imaginary property.
     * 
     * @return
     *     possible object is
     *     {@link ArithType }
     *     
     */
    public ArithType getImaginary() {
        return imaginary;
    }

    /**
     * Sets the value of the imaginary property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArithType }
     *     
     */
    public void setImaginary(ArithType value) {
        this.imaginary = value;
    }

    /**
     * Gets the value of the floor property.
     * 
     * @return
     *     possible object is
     *     {@link ArithType }
     *     
     */
    public ArithType getFloor() {
        return floor;
    }

    /**
     * Sets the value of the floor property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArithType }
     *     
     */
    public void setFloor(ArithType value) {
        this.floor = value;
    }

    /**
     * Gets the value of the ceiling property.
     * 
     * @return
     *     possible object is
     *     {@link ArithType }
     *     
     */
    public ArithType getCeiling() {
        return ceiling;
    }

    /**
     * Sets the value of the ceiling property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArithType }
     *     
     */
    public void setCeiling(ArithType value) {
        this.ceiling = value;
    }

    /**
     * Gets the value of the quotient property.
     * 
     * @return
     *     possible object is
     *     {@link ArithType }
     *     
     */
    public ArithType getQuotient() {
        return quotient;
    }

    /**
     * Sets the value of the quotient property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArithType }
     *     
     */
    public void setQuotient(ArithType value) {
        this.quotient = value;
    }

    /**
     * Gets the value of the divide property.
     * 
     * @return
     *     possible object is
     *     {@link ArithType }
     *     
     */
    public ArithType getDivide() {
        return divide;
    }

    /**
     * Sets the value of the divide property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArithType }
     *     
     */
    public void setDivide(ArithType value) {
        this.divide = value;
    }

    /**
     * Gets the value of the rem property.
     * 
     * @return
     *     possible object is
     *     {@link ArithType }
     *     
     */
    public ArithType getRem() {
        return rem;
    }

    /**
     * Sets the value of the rem property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArithType }
     *     
     */
    public void setRem(ArithType value) {
        this.rem = value;
    }

    /**
     * Gets the value of the minus property.
     * 
     * @return
     *     possible object is
     *     {@link ArithType }
     *     
     */
    public ArithType getMinus() {
        return minus;
    }

    /**
     * Sets the value of the minus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArithType }
     *     
     */
    public void setMinus(ArithType value) {
        this.minus = value;
    }

    /**
     * Gets the value of the plus property.
     * 
     * @return
     *     possible object is
     *     {@link ArithType }
     *     
     */
    public ArithType getPlus() {
        return plus;
    }

    /**
     * Sets the value of the plus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArithType }
     *     
     */
    public void setPlus(ArithType value) {
        this.plus = value;
    }

    /**
     * Gets the value of the times property.
     * 
     * @return
     *     possible object is
     *     {@link ArithType }
     *     
     */
    public ArithType getTimes() {
        return times;
    }

    /**
     * Sets the value of the times property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArithType }
     *     
     */
    public void setTimes(ArithType value) {
        this.times = value;
    }

    /**
     * Gets the value of the power property.
     * 
     * @return
     *     possible object is
     *     {@link ArithType }
     *     
     */
    public ArithType getPower() {
        return power;
    }

    /**
     * Sets the value of the power property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArithType }
     *     
     */
    public void setPower(ArithType value) {
        this.power = value;
    }

    /**
     * Gets the value of the root property.
     * 
     * @return
     *     possible object is
     *     {@link ArithType }
     *     
     */
    public ArithType getRoot() {
        return root;
    }

    /**
     * Sets the value of the root property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArithType }
     *     
     */
    public void setRoot(ArithType value) {
        this.root = value;
    }

    /**
     * Gets the value of the max property.
     * 
     * @return
     *     possible object is
     *     {@link ArithType }
     *     
     */
    public ArithType getMax() {
        return max;
    }

    /**
     * Sets the value of the max property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArithType }
     *     
     */
    public void setMax(ArithType value) {
        this.max = value;
    }

    /**
     * Gets the value of the min property.
     * 
     * @return
     *     possible object is
     *     {@link ArithType }
     *     
     */
    public ArithType getMin() {
        return min;
    }

    /**
     * Sets the value of the min property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArithType }
     *     
     */
    public void setMin(ArithType value) {
        this.min = value;
    }

    /**
     * Gets the value of the gcd property.
     * 
     * @return
     *     possible object is
     *     {@link ArithType }
     *     
     */
    public ArithType getGcd() {
        return gcd;
    }

    /**
     * Sets the value of the gcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArithType }
     *     
     */
    public void setGcd(ArithType value) {
        this.gcd = value;
    }

    /**
     * Gets the value of the lcm property.
     * 
     * @return
     *     possible object is
     *     {@link ArithType }
     *     
     */
    public ArithType getLcm() {
        return lcm;
    }

    /**
     * Sets the value of the lcm property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArithType }
     *     
     */
    public void setLcm(ArithType value) {
        this.lcm = value;
    }

    /**
     * Gets the value of the sum property.
     * 
     * @return
     *     possible object is
     *     {@link ArithType }
     *     
     */
    public ArithType getSum() {
        return sum;
    }

    /**
     * Sets the value of the sum property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArithType }
     *     
     */
    public void setSum(ArithType value) {
        this.sum = value;
    }

    /**
     * Gets the value of the product property.
     * 
     * @return
     *     possible object is
     *     {@link ArithType }
     *     
     */
    public ArithType getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArithType }
     *     
     */
    public void setProduct(ArithType value) {
        this.product = value;
    }

    /**
     * Gets the value of the compose property.
     * 
     * @return
     *     possible object is
     *     {@link FunctionsType }
     *     
     */
    public FunctionsType getCompose() {
        return compose;
    }

    /**
     * Sets the value of the compose property.
     * 
     * @param value
     *     allowed object is
     *     {@link FunctionsType }
     *     
     */
    public void setCompose(FunctionsType value) {
        this.compose = value;
    }

    /**
     * Gets the value of the domain property.
     * 
     * @return
     *     possible object is
     *     {@link FunctionsType }
     *     
     */
    public FunctionsType getDomain() {
        return domain;
    }

    /**
     * Sets the value of the domain property.
     * 
     * @param value
     *     allowed object is
     *     {@link FunctionsType }
     *     
     */
    public void setDomain(FunctionsType value) {
        this.domain = value;
    }

    /**
     * Gets the value of the codomain property.
     * 
     * @return
     *     possible object is
     *     {@link FunctionsType }
     *     
     */
    public FunctionsType getCodomain() {
        return codomain;
    }

    /**
     * Sets the value of the codomain property.
     * 
     * @param value
     *     allowed object is
     *     {@link FunctionsType }
     *     
     */
    public void setCodomain(FunctionsType value) {
        this.codomain = value;
    }

    /**
     * Gets the value of the image property.
     * 
     * @return
     *     possible object is
     *     {@link FunctionsType }
     *     
     */
    public FunctionsType getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *     allowed object is
     *     {@link FunctionsType }
     *     
     */
    public void setImage(FunctionsType value) {
        this.image = value;
    }

    /**
     * Gets the value of the domainofapplication property.
     * 
     * @return
     *     possible object is
     *     {@link DomainofapplicationType }
     *     
     */
    public DomainofapplicationType getDomainofapplication() {
        return domainofapplication;
    }

    /**
     * Sets the value of the domainofapplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomainofapplicationType }
     *     
     */
    public void setDomainofapplication(DomainofapplicationType value) {
        this.domainofapplication = value;
    }

    /**
     * Gets the value of the ident property.
     * 
     * @return
     *     possible object is
     *     {@link FunctionsType }
     *     
     */
    public FunctionsType getIdent() {
        return ident;
    }

    /**
     * Sets the value of the ident property.
     * 
     * @param value
     *     allowed object is
     *     {@link FunctionsType }
     *     
     */
    public void setIdent(FunctionsType value) {
        this.ident = value;
    }

    /**
     * Gets the value of the and property.
     * 
     * @return
     *     possible object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public ElementaryFunctionsType getAnd() {
        return and;
    }

    /**
     * Sets the value of the and property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public void setAnd(ElementaryFunctionsType value) {
        this.and = value;
    }

    /**
     * Gets the value of the or property.
     * 
     * @return
     *     possible object is
     *     {@link LogicType }
     *     
     */
    public LogicType getOr() {
        return or;
    }

    /**
     * Sets the value of the or property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogicType }
     *     
     */
    public void setOr(LogicType value) {
        this.or = value;
    }

    /**
     * Gets the value of the xor property.
     * 
     * @return
     *     possible object is
     *     {@link LogicType }
     *     
     */
    public LogicType getXor() {
        return xor;
    }

    /**
     * Sets the value of the xor property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogicType }
     *     
     */
    public void setXor(LogicType value) {
        this.xor = value;
    }

    /**
     * Gets the value of the not property.
     * 
     * @return
     *     possible object is
     *     {@link LogicType }
     *     
     */
    public LogicType getNot() {
        return not;
    }

    /**
     * Sets the value of the not property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogicType }
     *     
     */
    public void setNot(LogicType value) {
        this.not = value;
    }

    /**
     * Gets the value of the exists property.
     * 
     * @return
     *     possible object is
     *     {@link LogicType }
     *     
     */
    public LogicType getExists() {
        return exists;
    }

    /**
     * Sets the value of the exists property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogicType }
     *     
     */
    public void setExists(LogicType value) {
        this.exists = value;
    }

    /**
     * Gets the value of the forall property.
     * 
     * @return
     *     possible object is
     *     {@link LogicType }
     *     
     */
    public LogicType getForall() {
        return forall;
    }

    /**
     * Sets the value of the forall property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogicType }
     *     
     */
    public void setForall(LogicType value) {
        this.forall = value;
    }

    /**
     * Gets the value of the implies property.
     * 
     * @return
     *     possible object is
     *     {@link LogicType }
     *     
     */
    public LogicType getImplies() {
        return implies;
    }

    /**
     * Sets the value of the implies property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogicType }
     *     
     */
    public void setImplies(LogicType value) {
        this.implies = value;
    }

    /**
     * Gets the value of the naturalnumbers property.
     * 
     * @return
     *     possible object is
     *     {@link ConstantType }
     *     
     */
    public ConstantType getNaturalnumbers() {
        return naturalnumbers;
    }

    /**
     * Sets the value of the naturalnumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstantType }
     *     
     */
    public void setNaturalnumbers(ConstantType value) {
        this.naturalnumbers = value;
    }

    /**
     * Gets the value of the primes property.
     * 
     * @return
     *     possible object is
     *     {@link ConstantType }
     *     
     */
    public ConstantType getPrimes() {
        return primes;
    }

    /**
     * Sets the value of the primes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstantType }
     *     
     */
    public void setPrimes(ConstantType value) {
        this.primes = value;
    }

    /**
     * Gets the value of the integers property.
     * 
     * @return
     *     possible object is
     *     {@link ConstantType }
     *     
     */
    public ConstantType getIntegers() {
        return integers;
    }

    /**
     * Sets the value of the integers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstantType }
     *     
     */
    public void setIntegers(ConstantType value) {
        this.integers = value;
    }

    /**
     * Gets the value of the rationals property.
     * 
     * @return
     *     possible object is
     *     {@link ConstantType }
     *     
     */
    public ConstantType getRationals() {
        return rationals;
    }

    /**
     * Sets the value of the rationals property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstantType }
     *     
     */
    public void setRationals(ConstantType value) {
        this.rationals = value;
    }

    /**
     * Gets the value of the reals property.
     * 
     * @return
     *     possible object is
     *     {@link ConstantType }
     *     
     */
    public ConstantType getReals() {
        return reals;
    }

    /**
     * Sets the value of the reals property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstantType }
     *     
     */
    public void setReals(ConstantType value) {
        this.reals = value;
    }

    /**
     * Gets the value of the complexes property.
     * 
     * @return
     *     possible object is
     *     {@link ConstantType }
     *     
     */
    public ConstantType getComplexes() {
        return complexes;
    }

    /**
     * Sets the value of the complexes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstantType }
     *     
     */
    public void setComplexes(ConstantType value) {
        this.complexes = value;
    }

    /**
     * Gets the value of the emptyset property.
     * 
     * @return
     *     possible object is
     *     {@link ConstantType }
     *     
     */
    public ConstantType getEmptyset() {
        return emptyset;
    }

    /**
     * Sets the value of the emptyset property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstantType }
     *     
     */
    public void setEmptyset(ConstantType value) {
        this.emptyset = value;
    }

    /**
     * Gets the value of the exponentiale property.
     * 
     * @return
     *     possible object is
     *     {@link ConstantType }
     *     
     */
    public ConstantType getExponentiale() {
        return exponentiale;
    }

    /**
     * Sets the value of the exponentiale property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstantType }
     *     
     */
    public void setExponentiale(ConstantType value) {
        this.exponentiale = value;
    }

    /**
     * Gets the value of the imaginaryi property.
     * 
     * @return
     *     possible object is
     *     {@link ConstantType }
     *     
     */
    public ConstantType getImaginaryi() {
        return imaginaryi;
    }

    /**
     * Sets the value of the imaginaryi property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstantType }
     *     
     */
    public void setImaginaryi(ConstantType value) {
        this.imaginaryi = value;
    }

    /**
     * Gets the value of the pi property.
     * 
     * @return
     *     possible object is
     *     {@link ConstantType }
     *     
     */
    public ConstantType getPi() {
        return pi;
    }

    /**
     * Sets the value of the pi property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstantType }
     *     
     */
    public void setPi(ConstantType value) {
        this.pi = value;
    }

    /**
     * Gets the value of the eulergamma property.
     * 
     * @return
     *     possible object is
     *     {@link ConstantType }
     *     
     */
    public ConstantType getEulergamma() {
        return eulergamma;
    }

    /**
     * Sets the value of the eulergamma property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstantType }
     *     
     */
    public void setEulergamma(ConstantType value) {
        this.eulergamma = value;
    }

    /**
     * Gets the value of the true property.
     * 
     * @return
     *     possible object is
     *     {@link ConstantType }
     *     
     */
    public ConstantType getTrue() {
        return _true;
    }

    /**
     * Sets the value of the true property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstantType }
     *     
     */
    public void setTrue(ConstantType value) {
        this._true = value;
    }

    /**
     * Gets the value of the false property.
     * 
     * @return
     *     possible object is
     *     {@link ConstantType }
     *     
     */
    public ConstantType getFalse() {
        return _false;
    }

    /**
     * Sets the value of the false property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstantType }
     *     
     */
    public void setFalse(ConstantType value) {
        this._false = value;
    }

    /**
     * Gets the value of the infinity property.
     * 
     * @return
     *     possible object is
     *     {@link ConstantType }
     *     
     */
    public ConstantType getInfinity() {
        return infinity;
    }

    /**
     * Sets the value of the infinity property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstantType }
     *     
     */
    public void setInfinity(ConstantType value) {
        this.infinity = value;
    }

    /**
     * Gets the value of the notanumber property.
     * 
     * @return
     *     possible object is
     *     {@link ConstantType }
     *     
     */
    public ConstantType getNotanumber() {
        return notanumber;
    }

    /**
     * Sets the value of the notanumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstantType }
     *     
     */
    public void setNotanumber(ConstantType value) {
        this.notanumber = value;
    }

    /**
     * Gets the value of the set property.
     * 
     * @return
     *     possible object is
     *     {@link SetType }
     *     
     */
    public SetType getSet() {
        return set;
    }

    /**
     * Sets the value of the set property.
     * 
     * @param value
     *     allowed object is
     *     {@link SetType }
     *     
     */
    public void setSet(SetType value) {
        this.set = value;
    }

    /**
     * Gets the value of the list property.
     * 
     * @return
     *     possible object is
     *     {@link ListType }
     *     
     */
    public ListType getList() {
        return list;
    }

    /**
     * Sets the value of the list property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListType }
     *     
     */
    public void setList(ListType value) {
        this.list = value;
    }

    /**
     * Gets the value of the union property.
     * 
     * @return
     *     possible object is
     *     {@link UnionType }
     *     
     */
    public UnionType getUnion() {
        return union;
    }

    /**
     * Sets the value of the union property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnionType }
     *     
     */
    public void setUnion(UnionType value) {
        this.union = value;
    }

    /**
     * Gets the value of the intersect property.
     * 
     * @return
     *     possible object is
     *     {@link IntersectType }
     *     
     */
    public IntersectType getIntersect() {
        return intersect;
    }

    /**
     * Sets the value of the intersect property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntersectType }
     *     
     */
    public void setIntersect(IntersectType value) {
        this.intersect = value;
    }

    /**
     * Gets the value of the in property.
     * 
     * @return
     *     possible object is
     *     {@link InType }
     *     
     */
    public InType getIn() {
        return in;
    }

    /**
     * Sets the value of the in property.
     * 
     * @param value
     *     allowed object is
     *     {@link InType }
     *     
     */
    public void setIn(InType value) {
        this.in = value;
    }

    /**
     * Gets the value of the notin property.
     * 
     * @return
     *     possible object is
     *     {@link NotinType }
     *     
     */
    public NotinType getNotin() {
        return notin;
    }

    /**
     * Sets the value of the notin property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotinType }
     *     
     */
    public void setNotin(NotinType value) {
        this.notin = value;
    }

    /**
     * Gets the value of the subset property.
     * 
     * @return
     *     possible object is
     *     {@link SubsetType }
     *     
     */
    public SubsetType getSubset() {
        return subset;
    }

    /**
     * Sets the value of the subset property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubsetType }
     *     
     */
    public void setSubset(SubsetType value) {
        this.subset = value;
    }

    /**
     * Gets the value of the prsubset property.
     * 
     * @return
     *     possible object is
     *     {@link PrsubsetType }
     *     
     */
    public PrsubsetType getPrsubset() {
        return prsubset;
    }

    /**
     * Sets the value of the prsubset property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrsubsetType }
     *     
     */
    public void setPrsubset(PrsubsetType value) {
        this.prsubset = value;
    }

    /**
     * Gets the value of the notsubset property.
     * 
     * @return
     *     possible object is
     *     {@link NotsubsetType }
     *     
     */
    public NotsubsetType getNotsubset() {
        return notsubset;
    }

    /**
     * Sets the value of the notsubset property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotsubsetType }
     *     
     */
    public void setNotsubset(NotsubsetType value) {
        this.notsubset = value;
    }

    /**
     * Gets the value of the notprsubset property.
     * 
     * @return
     *     possible object is
     *     {@link NotprsubsetType }
     *     
     */
    public NotprsubsetType getNotprsubset() {
        return notprsubset;
    }

    /**
     * Sets the value of the notprsubset property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotprsubsetType }
     *     
     */
    public void setNotprsubset(NotprsubsetType value) {
        this.notprsubset = value;
    }

    /**
     * Gets the value of the setdiff property.
     * 
     * @return
     *     possible object is
     *     {@link SetdiffType }
     *     
     */
    public SetdiffType getSetdiff() {
        return setdiff;
    }

    /**
     * Sets the value of the setdiff property.
     * 
     * @param value
     *     allowed object is
     *     {@link SetdiffType }
     *     
     */
    public void setSetdiff(SetdiffType value) {
        this.setdiff = value;
    }

    /**
     * Gets the value of the card property.
     * 
     * @return
     *     possible object is
     *     {@link CardType }
     *     
     */
    public CardType getCard() {
        return card;
    }

    /**
     * Sets the value of the card property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardType }
     *     
     */
    public void setCard(CardType value) {
        this.card = value;
    }

    /**
     * Gets the value of the cartesianproduct property.
     * 
     * @return
     *     possible object is
     *     {@link CartesianproductType }
     *     
     */
    public CartesianproductType getCartesianproduct() {
        return cartesianproduct;
    }

    /**
     * Sets the value of the cartesianproduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link CartesianproductType }
     *     
     */
    public void setCartesianproduct(CartesianproductType value) {
        this.cartesianproduct = value;
    }

    /**
     * Gets the value of the eq property.
     * 
     * @return
     *     possible object is
     *     {@link RelationsType }
     *     
     */
    public RelationsType getEq() {
        return eq;
    }

    /**
     * Sets the value of the eq property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationsType }
     *     
     */
    public void setEq(RelationsType value) {
        this.eq = value;
    }

    /**
     * Gets the value of the neq property.
     * 
     * @return
     *     possible object is
     *     {@link RelationsType }
     *     
     */
    public RelationsType getNeq() {
        return neq;
    }

    /**
     * Sets the value of the neq property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationsType }
     *     
     */
    public void setNeq(RelationsType value) {
        this.neq = value;
    }

    /**
     * Gets the value of the leq property.
     * 
     * @return
     *     possible object is
     *     {@link RelationsType }
     *     
     */
    public RelationsType getLeq() {
        return leq;
    }

    /**
     * Sets the value of the leq property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationsType }
     *     
     */
    public void setLeq(RelationsType value) {
        this.leq = value;
    }

    /**
     * Gets the value of the lt property.
     * 
     * @return
     *     possible object is
     *     {@link RelationsType }
     *     
     */
    public RelationsType getLt() {
        return lt;
    }

    /**
     * Sets the value of the lt property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationsType }
     *     
     */
    public void setLt(RelationsType value) {
        this.lt = value;
    }

    /**
     * Gets the value of the geq property.
     * 
     * @return
     *     possible object is
     *     {@link RelationsType }
     *     
     */
    public RelationsType getGeq() {
        return geq;
    }

    /**
     * Sets the value of the geq property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationsType }
     *     
     */
    public void setGeq(RelationsType value) {
        this.geq = value;
    }

    /**
     * Gets the value of the gt property.
     * 
     * @return
     *     possible object is
     *     {@link RelationsType }
     *     
     */
    public RelationsType getGt() {
        return gt;
    }

    /**
     * Sets the value of the gt property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationsType }
     *     
     */
    public void setGt(RelationsType value) {
        this.gt = value;
    }

    /**
     * Gets the value of the equivalent property.
     * 
     * @return
     *     possible object is
     *     {@link RelationsType }
     *     
     */
    public RelationsType getEquivalent() {
        return equivalent;
    }

    /**
     * Sets the value of the equivalent property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationsType }
     *     
     */
    public void setEquivalent(RelationsType value) {
        this.equivalent = value;
    }

    /**
     * Gets the value of the approx property.
     * 
     * @return
     *     possible object is
     *     {@link RelationsType }
     *     
     */
    public RelationsType getApprox() {
        return approx;
    }

    /**
     * Sets the value of the approx property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationsType }
     *     
     */
    public void setApprox(RelationsType value) {
        this.approx = value;
    }

    /**
     * Gets the value of the factorof property.
     * 
     * @return
     *     possible object is
     *     {@link RelationsType }
     *     
     */
    public RelationsType getFactorof() {
        return factorof;
    }

    /**
     * Sets the value of the factorof property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationsType }
     *     
     */
    public void setFactorof(RelationsType value) {
        this.factorof = value;
    }

    /**
     * Gets the value of the exp property.
     * 
     * @return
     *     possible object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public ElementaryFunctionsType getExp() {
        return exp;
    }

    /**
     * Sets the value of the exp property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public void setExp(ElementaryFunctionsType value) {
        this.exp = value;
    }

    /**
     * Gets the value of the ln property.
     * 
     * @return
     *     possible object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public ElementaryFunctionsType getLn() {
        return ln;
    }

    /**
     * Sets the value of the ln property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public void setLn(ElementaryFunctionsType value) {
        this.ln = value;
    }

    /**
     * Gets the value of the log property.
     * 
     * @return
     *     possible object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public ElementaryFunctionsType getLog() {
        return log;
    }

    /**
     * Sets the value of the log property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public void setLog(ElementaryFunctionsType value) {
        this.log = value;
    }

    /**
     * Gets the value of the logbase property.
     * 
     * @return
     *     possible object is
     *     {@link LogbaseType }
     *     
     */
    public LogbaseType getLogbase() {
        return logbase;
    }

    /**
     * Sets the value of the logbase property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogbaseType }
     *     
     */
    public void setLogbase(LogbaseType value) {
        this.logbase = value;
    }

    /**
     * Gets the value of the sin property.
     * 
     * @return
     *     possible object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public ElementaryFunctionsType getSin() {
        return sin;
    }

    /**
     * Sets the value of the sin property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public void setSin(ElementaryFunctionsType value) {
        this.sin = value;
    }

    /**
     * Gets the value of the cos property.
     * 
     * @return
     *     possible object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public ElementaryFunctionsType getCos() {
        return cos;
    }

    /**
     * Sets the value of the cos property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public void setCos(ElementaryFunctionsType value) {
        this.cos = value;
    }

    /**
     * Gets the value of the tan property.
     * 
     * @return
     *     possible object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public ElementaryFunctionsType getTan() {
        return tan;
    }

    /**
     * Sets the value of the tan property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public void setTan(ElementaryFunctionsType value) {
        this.tan = value;
    }

    /**
     * Gets the value of the sec property.
     * 
     * @return
     *     possible object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public ElementaryFunctionsType getSec() {
        return sec;
    }

    /**
     * Sets the value of the sec property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public void setSec(ElementaryFunctionsType value) {
        this.sec = value;
    }

    /**
     * Gets the value of the csc property.
     * 
     * @return
     *     possible object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public ElementaryFunctionsType getCsc() {
        return csc;
    }

    /**
     * Sets the value of the csc property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public void setCsc(ElementaryFunctionsType value) {
        this.csc = value;
    }

    /**
     * Gets the value of the cot property.
     * 
     * @return
     *     possible object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public ElementaryFunctionsType getCot() {
        return cot;
    }

    /**
     * Sets the value of the cot property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public void setCot(ElementaryFunctionsType value) {
        this.cot = value;
    }

    /**
     * Gets the value of the arcsin property.
     * 
     * @return
     *     possible object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public ElementaryFunctionsType getArcsin() {
        return arcsin;
    }

    /**
     * Sets the value of the arcsin property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public void setArcsin(ElementaryFunctionsType value) {
        this.arcsin = value;
    }

    /**
     * Gets the value of the arccos property.
     * 
     * @return
     *     possible object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public ElementaryFunctionsType getArccos() {
        return arccos;
    }

    /**
     * Sets the value of the arccos property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public void setArccos(ElementaryFunctionsType value) {
        this.arccos = value;
    }

    /**
     * Gets the value of the arctan property.
     * 
     * @return
     *     possible object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public ElementaryFunctionsType getArctan() {
        return arctan;
    }

    /**
     * Sets the value of the arctan property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public void setArctan(ElementaryFunctionsType value) {
        this.arctan = value;
    }

    /**
     * Gets the value of the arcsec property.
     * 
     * @return
     *     possible object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public ElementaryFunctionsType getArcsec() {
        return arcsec;
    }

    /**
     * Sets the value of the arcsec property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public void setArcsec(ElementaryFunctionsType value) {
        this.arcsec = value;
    }

    /**
     * Gets the value of the arccsc property.
     * 
     * @return
     *     possible object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public ElementaryFunctionsType getArccsc() {
        return arccsc;
    }

    /**
     * Sets the value of the arccsc property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public void setArccsc(ElementaryFunctionsType value) {
        this.arccsc = value;
    }

    /**
     * Gets the value of the arccot property.
     * 
     * @return
     *     possible object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public ElementaryFunctionsType getArccot() {
        return arccot;
    }

    /**
     * Sets the value of the arccot property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public void setArccot(ElementaryFunctionsType value) {
        this.arccot = value;
    }

    /**
     * Gets the value of the sinh property.
     * 
     * @return
     *     possible object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public ElementaryFunctionsType getSinh() {
        return sinh;
    }

    /**
     * Sets the value of the sinh property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public void setSinh(ElementaryFunctionsType value) {
        this.sinh = value;
    }

    /**
     * Gets the value of the cosh property.
     * 
     * @return
     *     possible object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public ElementaryFunctionsType getCosh() {
        return cosh;
    }

    /**
     * Sets the value of the cosh property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public void setCosh(ElementaryFunctionsType value) {
        this.cosh = value;
    }

    /**
     * Gets the value of the tanh property.
     * 
     * @return
     *     possible object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public ElementaryFunctionsType getTanh() {
        return tanh;
    }

    /**
     * Sets the value of the tanh property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public void setTanh(ElementaryFunctionsType value) {
        this.tanh = value;
    }

    /**
     * Gets the value of the sech property.
     * 
     * @return
     *     possible object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public ElementaryFunctionsType getSech() {
        return sech;
    }

    /**
     * Sets the value of the sech property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public void setSech(ElementaryFunctionsType value) {
        this.sech = value;
    }

    /**
     * Gets the value of the csch property.
     * 
     * @return
     *     possible object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public ElementaryFunctionsType getCsch() {
        return csch;
    }

    /**
     * Sets the value of the csch property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public void setCsch(ElementaryFunctionsType value) {
        this.csch = value;
    }

    /**
     * Gets the value of the coth property.
     * 
     * @return
     *     possible object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public ElementaryFunctionsType getCoth() {
        return coth;
    }

    /**
     * Sets the value of the coth property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public void setCoth(ElementaryFunctionsType value) {
        this.coth = value;
    }

    /**
     * Gets the value of the arccosh property.
     * 
     * @return
     *     possible object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public ElementaryFunctionsType getArccosh() {
        return arccosh;
    }

    /**
     * Sets the value of the arccosh property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public void setArccosh(ElementaryFunctionsType value) {
        this.arccosh = value;
    }

    /**
     * Gets the value of the arccoth property.
     * 
     * @return
     *     possible object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public ElementaryFunctionsType getArccoth() {
        return arccoth;
    }

    /**
     * Sets the value of the arccoth property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public void setArccoth(ElementaryFunctionsType value) {
        this.arccoth = value;
    }

    /**
     * Gets the value of the arccsch property.
     * 
     * @return
     *     possible object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public ElementaryFunctionsType getArccsch() {
        return arccsch;
    }

    /**
     * Sets the value of the arccsch property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public void setArccsch(ElementaryFunctionsType value) {
        this.arccsch = value;
    }

    /**
     * Gets the value of the arcsech property.
     * 
     * @return
     *     possible object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public ElementaryFunctionsType getArcsech() {
        return arcsech;
    }

    /**
     * Sets the value of the arcsech property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public void setArcsech(ElementaryFunctionsType value) {
        this.arcsech = value;
    }

    /**
     * Gets the value of the arcsinh property.
     * 
     * @return
     *     possible object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public ElementaryFunctionsType getArcsinh() {
        return arcsinh;
    }

    /**
     * Sets the value of the arcsinh property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public void setArcsinh(ElementaryFunctionsType value) {
        this.arcsinh = value;
    }

    /**
     * Gets the value of the arctanh property.
     * 
     * @return
     *     possible object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public ElementaryFunctionsType getArctanh() {
        return arctanh;
    }

    /**
     * Sets the value of the arctanh property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementaryFunctionsType }
     *     
     */
    public void setArctanh(ElementaryFunctionsType value) {
        this.arctanh = value;
    }

    /**
     * Gets the value of the int property.
     * 
     * @return
     *     possible object is
     *     {@link IntType }
     *     
     */
    public IntType getInt() {
        return _int;
    }

    /**
     * Sets the value of the int property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntType }
     *     
     */
    public void setInt(IntType value) {
        this._int = value;
    }

    /**
     * Gets the value of the diff property.
     * 
     * @return
     *     possible object is
     *     {@link DiffType }
     *     
     */
    public DiffType getDiff() {
        return diff;
    }

    /**
     * Sets the value of the diff property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiffType }
     *     
     */
    public void setDiff(DiffType value) {
        this.diff = value;
    }

    /**
     * Gets the value of the partialdiff property.
     * 
     * @return
     *     possible object is
     *     {@link PartialdiffType }
     *     
     */
    public PartialdiffType getPartialdiff() {
        return partialdiff;
    }

    /**
     * Sets the value of the partialdiff property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartialdiffType }
     *     
     */
    public void setPartialdiff(PartialdiffType value) {
        this.partialdiff = value;
    }

    /**
     * Gets the value of the limit property.
     * 
     * @return
     *     possible object is
     *     {@link LimitType }
     *     
     */
    public LimitType getLimit() {
        return limit;
    }

    /**
     * Sets the value of the limit property.
     * 
     * @param value
     *     allowed object is
     *     {@link LimitType }
     *     
     */
    public void setLimit(LimitType value) {
        this.limit = value;
    }

    /**
     * Gets the value of the lowlimit property.
     * 
     * @return
     *     possible object is
     *     {@link LowlimitType }
     *     
     */
    public LowlimitType getLowlimit() {
        return lowlimit;
    }

    /**
     * Sets the value of the lowlimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link LowlimitType }
     *     
     */
    public void setLowlimit(LowlimitType value) {
        this.lowlimit = value;
    }

    /**
     * Gets the value of the uplimit property.
     * 
     * @return
     *     possible object is
     *     {@link UplimitType }
     *     
     */
    public UplimitType getUplimit() {
        return uplimit;
    }

    /**
     * Sets the value of the uplimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link UplimitType }
     *     
     */
    public void setUplimit(UplimitType value) {
        this.uplimit = value;
    }

    /**
     * Gets the value of the tendsto property.
     * 
     * @return
     *     possible object is
     *     {@link TendstoType }
     *     
     */
    public TendstoType getTendsto() {
        return tendsto;
    }

    /**
     * Sets the value of the tendsto property.
     * 
     * @param value
     *     allowed object is
     *     {@link TendstoType }
     *     
     */
    public void setTendsto(TendstoType value) {
        this.tendsto = value;
    }

    /**
     * Gets the value of the vector property.
     * 
     * @return
     *     possible object is
     *     {@link VectorType }
     *     
     */
    public VectorType getVector() {
        return vector;
    }

    /**
     * Sets the value of the vector property.
     * 
     * @param value
     *     allowed object is
     *     {@link VectorType }
     *     
     */
    public void setVector(VectorType value) {
        this.vector = value;
    }

    /**
     * Gets the value of the matrix property.
     * 
     * @return
     *     possible object is
     *     {@link MatrixType }
     *     
     */
    public MatrixType getMatrix() {
        return matrix;
    }

    /**
     * Sets the value of the matrix property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatrixType }
     *     
     */
    public void setMatrix(MatrixType value) {
        this.matrix = value;
    }

    /**
     * Gets the value of the determinant property.
     * 
     * @return
     *     possible object is
     *     {@link DeterminantType }
     *     
     */
    public DeterminantType getDeterminant() {
        return determinant;
    }

    /**
     * Sets the value of the determinant property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeterminantType }
     *     
     */
    public void setDeterminant(DeterminantType value) {
        this.determinant = value;
    }

    /**
     * Gets the value of the transpose property.
     * 
     * @return
     *     possible object is
     *     {@link TransposeType }
     *     
     */
    public TransposeType getTranspose() {
        return transpose;
    }

    /**
     * Sets the value of the transpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransposeType }
     *     
     */
    public void setTranspose(TransposeType value) {
        this.transpose = value;
    }

    /**
     * Gets the value of the selector property.
     * 
     * @return
     *     possible object is
     *     {@link SelectorType }
     *     
     */
    public SelectorType getSelector() {
        return selector;
    }

    /**
     * Sets the value of the selector property.
     * 
     * @param value
     *     allowed object is
     *     {@link SelectorType }
     *     
     */
    public void setSelector(SelectorType value) {
        this.selector = value;
    }

    /**
     * Gets the value of the vectorproduct property.
     * 
     * @return
     *     possible object is
     *     {@link VectorproductType }
     *     
     */
    public VectorproductType getVectorproduct() {
        return vectorproduct;
    }

    /**
     * Sets the value of the vectorproduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link VectorproductType }
     *     
     */
    public void setVectorproduct(VectorproductType value) {
        this.vectorproduct = value;
    }

    /**
     * Gets the value of the scalarproduct property.
     * 
     * @return
     *     possible object is
     *     {@link ScalarproductType }
     *     
     */
    public ScalarproductType getScalarproduct() {
        return scalarproduct;
    }

    /**
     * Sets the value of the scalarproduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScalarproductType }
     *     
     */
    public void setScalarproduct(ScalarproductType value) {
        this.scalarproduct = value;
    }

    /**
     * Gets the value of the outerproduct property.
     * 
     * @return
     *     possible object is
     *     {@link OuterproductType }
     *     
     */
    public OuterproductType getOuterproduct() {
        return outerproduct;
    }

    /**
     * Sets the value of the outerproduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link OuterproductType }
     *     
     */
    public void setOuterproduct(OuterproductType value) {
        this.outerproduct = value;
    }

    /**
     * Gets the value of the divergence property.
     * 
     * @return
     *     possible object is
     *     {@link DivergenceType }
     *     
     */
    public DivergenceType getDivergence() {
        return divergence;
    }

    /**
     * Sets the value of the divergence property.
     * 
     * @param value
     *     allowed object is
     *     {@link DivergenceType }
     *     
     */
    public void setDivergence(DivergenceType value) {
        this.divergence = value;
    }

    /**
     * Gets the value of the grad property.
     * 
     * @return
     *     possible object is
     *     {@link GradType }
     *     
     */
    public GradType getGrad() {
        return grad;
    }

    /**
     * Sets the value of the grad property.
     * 
     * @param value
     *     allowed object is
     *     {@link GradType }
     *     
     */
    public void setGrad(GradType value) {
        this.grad = value;
    }

    /**
     * Gets the value of the curl property.
     * 
     * @return
     *     possible object is
     *     {@link CurlType }
     *     
     */
    public CurlType getCurl() {
        return curl;
    }

    /**
     * Sets the value of the curl property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurlType }
     *     
     */
    public void setCurl(CurlType value) {
        this.curl = value;
    }

    /**
     * Gets the value of the laplacian property.
     * 
     * @return
     *     possible object is
     *     {@link LaplacianType }
     *     
     */
    public LaplacianType getLaplacian() {
        return laplacian;
    }

    /**
     * Sets the value of the laplacian property.
     * 
     * @param value
     *     allowed object is
     *     {@link LaplacianType }
     *     
     */
    public void setLaplacian(LaplacianType value) {
        this.laplacian = value;
    }

    /**
     * Gets the value of the mean property.
     * 
     * @return
     *     possible object is
     *     {@link MeanType }
     *     
     */
    public MeanType getMean() {
        return mean;
    }

    /**
     * Sets the value of the mean property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeanType }
     *     
     */
    public void setMean(MeanType value) {
        this.mean = value;
    }

    /**
     * Gets the value of the sdev property.
     * 
     * @return
     *     possible object is
     *     {@link SdevType }
     *     
     */
    public SdevType getSdev() {
        return sdev;
    }

    /**
     * Sets the value of the sdev property.
     * 
     * @param value
     *     allowed object is
     *     {@link SdevType }
     *     
     */
    public void setSdev(SdevType value) {
        this.sdev = value;
    }

    /**
     * Gets the value of the variance property.
     * 
     * @return
     *     possible object is
     *     {@link VarianceType }
     *     
     */
    public VarianceType getVariance() {
        return variance;
    }

    /**
     * Sets the value of the variance property.
     * 
     * @param value
     *     allowed object is
     *     {@link VarianceType }
     *     
     */
    public void setVariance(VarianceType value) {
        this.variance = value;
    }

    /**
     * Gets the value of the median property.
     * 
     * @return
     *     possible object is
     *     {@link MedianType }
     *     
     */
    public MedianType getMedian() {
        return median;
    }

    /**
     * Sets the value of the median property.
     * 
     * @param value
     *     allowed object is
     *     {@link MedianType }
     *     
     */
    public void setMedian(MedianType value) {
        this.median = value;
    }

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link ModeType }
     *     
     */
    public ModeType getMode() {
        return mode;
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModeType }
     *     
     */
    public void setMode(ModeType value) {
        this.mode = value;
    }

    /**
     * Gets the value of the moment property.
     * 
     * @return
     *     possible object is
     *     {@link MomentType }
     *     
     */
    public MomentType getMoment() {
        return moment;
    }

    /**
     * Sets the value of the moment property.
     * 
     * @param value
     *     allowed object is
     *     {@link MomentType }
     *     
     */
    public void setMoment(MomentType value) {
        this.moment = value;
    }

    /**
     * Gets the value of the momentabout property.
     * 
     * @return
     *     possible object is
     *     {@link MomentaboutType }
     *     
     */
    public MomentaboutType getMomentabout() {
        return momentabout;
    }

    /**
     * Sets the value of the momentabout property.
     * 
     * @param value
     *     allowed object is
     *     {@link MomentaboutType }
     *     
     */
    public void setMomentabout(MomentaboutType value) {
        this.momentabout = value;
    }

    /**
     * Gets the value of the apply property.
     * 
     * @return
     *     possible object is
     *     {@link ApplyType }
     *     
     */
    public ApplyType getApply() {
        return apply;
    }

    /**
     * Sets the value of the apply property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplyType }
     *     
     */
    public void setApply(ApplyType value) {
        this.apply = value;
    }

    /**
     * Gets the value of the interval property.
     * 
     * @return
     *     possible object is
     *     {@link IntervalType }
     *     
     */
    public IntervalType getInterval() {
        return interval;
    }

    /**
     * Sets the value of the interval property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntervalType }
     *     
     */
    public void setInterval(IntervalType value) {
        this.interval = value;
    }

    /**
     * Gets the value of the inverse property.
     * 
     * @return
     *     possible object is
     *     {@link InverseType }
     *     
     */
    public InverseType getInverse() {
        return inverse;
    }

    /**
     * Sets the value of the inverse property.
     * 
     * @param value
     *     allowed object is
     *     {@link InverseType }
     *     
     */
    public void setInverse(InverseType value) {
        this.inverse = value;
    }

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link ConditionType }
     *     
     */
    public ConditionType getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConditionType }
     *     
     */
    public void setCondition(ConditionType value) {
        this.condition = value;
    }

    /**
     * Gets the value of the declare property.
     * 
     * @return
     *     possible object is
     *     {@link DeclareType }
     *     
     */
    public DeclareType getDeclare() {
        return declare;
    }

    /**
     * Sets the value of the declare property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeclareType }
     *     
     */
    public void setDeclare(DeclareType value) {
        this.declare = value;
    }

    /**
     * Gets the value of the lambda property.
     * 
     * @return
     *     possible object is
     *     {@link LambdaType }
     *     
     */
    public LambdaType getLambda() {
        return lambda;
    }

    /**
     * Sets the value of the lambda property.
     * 
     * @param value
     *     allowed object is
     *     {@link LambdaType }
     *     
     */
    public void setLambda(LambdaType value) {
        this.lambda = value;
    }

    /**
     * Gets the value of the piecewise property.
     * 
     * @return
     *     possible object is
     *     {@link PiecewiseType }
     *     
     */
    public PiecewiseType getPiecewise() {
        return piecewise;
    }

    /**
     * Sets the value of the piecewise property.
     * 
     * @param value
     *     allowed object is
     *     {@link PiecewiseType }
     *     
     */
    public void setPiecewise(PiecewiseType value) {
        this.piecewise = value;
    }

    /**
     * Gets the value of the bvar property.
     * 
     * @return
     *     possible object is
     *     {@link BvarType }
     *     
     */
    public BvarType getBvar() {
        return bvar;
    }

    /**
     * Sets the value of the bvar property.
     * 
     * @param value
     *     allowed object is
     *     {@link BvarType }
     *     
     */
    public void setBvar(BvarType value) {
        this.bvar = value;
    }

    /**
     * Gets the value of the degree property.
     * 
     * @return
     *     possible object is
     *     {@link DegreeType }
     *     
     */
    public DegreeType getDegree() {
        return degree;
    }

    /**
     * Sets the value of the degree property.
     * 
     * @param value
     *     allowed object is
     *     {@link DegreeType }
     *     
     */
    public void setDegree(DegreeType value) {
        this.degree = value;
    }

    /**
     * Gets the value of the semantics property.
     * 
     * @return
     *     possible object is
     *     {@link SemanticsType }
     *     
     */
    public SemanticsType getSemantics() {
        return semantics;
    }

    /**
     * Sets the value of the semantics property.
     * 
     * @param value
     *     allowed object is
     *     {@link SemanticsType }
     *     
     */
    public void setSemantics(SemanticsType value) {
        this.semantics = value;
    }

    /**
     * Gets the value of the mi property.
     * 
     * @return
     *     possible object is
     *     {@link MiType }
     *     
     */
    public MiType getMi() {
        return mi;
    }

    /**
     * Sets the value of the mi property.
     * 
     * @param value
     *     allowed object is
     *     {@link MiType }
     *     
     */
    public void setMi(MiType value) {
        this.mi = value;
    }

    /**
     * Gets the value of the mo property.
     * 
     * @return
     *     possible object is
     *     {@link MoType }
     *     
     */
    public MoType getMo() {
        return mo;
    }

    /**
     * Sets the value of the mo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MoType }
     *     
     */
    public void setMo(MoType value) {
        this.mo = value;
    }

    /**
     * Gets the value of the mn property.
     * 
     * @return
     *     possible object is
     *     {@link MnType }
     *     
     */
    public MnType getMn() {
        return mn;
    }

    /**
     * Sets the value of the mn property.
     * 
     * @param value
     *     allowed object is
     *     {@link MnType }
     *     
     */
    public void setMn(MnType value) {
        this.mn = value;
    }

    /**
     * Gets the value of the mtext property.
     * 
     * @return
     *     possible object is
     *     {@link MtextType }
     *     
     */
    public MtextType getMtext() {
        return mtext;
    }

    /**
     * Sets the value of the mtext property.
     * 
     * @param value
     *     allowed object is
     *     {@link MtextType }
     *     
     */
    public void setMtext(MtextType value) {
        this.mtext = value;
    }

    /**
     * Gets the value of the ms property.
     * 
     * @return
     *     possible object is
     *     {@link MsType }
     *     
     */
    public MsType getMs() {
        return ms;
    }

    /**
     * Sets the value of the ms property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsType }
     *     
     */
    public void setMs(MsType value) {
        this.ms = value;
    }

    /**
     * Gets the value of the mrow property.
     * 
     * @return
     *     possible object is
     *     {@link MrowType }
     *     
     */
    public MrowType getMrow() {
        return mrow;
    }

    /**
     * Sets the value of the mrow property.
     * 
     * @param value
     *     allowed object is
     *     {@link MrowType }
     *     
     */
    public void setMrow(MrowType value) {
        this.mrow = value;
    }

    /**
     * Gets the value of the mfrac property.
     * 
     * @return
     *     possible object is
     *     {@link MfracType }
     *     
     */
    public MfracType getMfrac() {
        return mfrac;
    }

    /**
     * Sets the value of the mfrac property.
     * 
     * @param value
     *     allowed object is
     *     {@link MfracType }
     *     
     */
    public void setMfrac(MfracType value) {
        this.mfrac = value;
    }

    /**
     * Gets the value of the msqrt property.
     * 
     * @return
     *     possible object is
     *     {@link MsqrtType }
     *     
     */
    public MsqrtType getMsqrt() {
        return msqrt;
    }

    /**
     * Sets the value of the msqrt property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsqrtType }
     *     
     */
    public void setMsqrt(MsqrtType value) {
        this.msqrt = value;
    }

    /**
     * Gets the value of the mroot property.
     * 
     * @return
     *     possible object is
     *     {@link MrootType }
     *     
     */
    public MrootType getMroot() {
        return mroot;
    }

    /**
     * Sets the value of the mroot property.
     * 
     * @param value
     *     allowed object is
     *     {@link MrootType }
     *     
     */
    public void setMroot(MrootType value) {
        this.mroot = value;
    }

    /**
     * Gets the value of the mpadded property.
     * 
     * @return
     *     possible object is
     *     {@link MpaddedType }
     *     
     */
    public MpaddedType getMpadded() {
        return mpadded;
    }

    /**
     * Sets the value of the mpadded property.
     * 
     * @param value
     *     allowed object is
     *     {@link MpaddedType }
     *     
     */
    public void setMpadded(MpaddedType value) {
        this.mpadded = value;
    }

    /**
     * Gets the value of the mphantom property.
     * 
     * @return
     *     possible object is
     *     {@link MphantomType }
     *     
     */
    public MphantomType getMphantom() {
        return mphantom;
    }

    /**
     * Sets the value of the mphantom property.
     * 
     * @param value
     *     allowed object is
     *     {@link MphantomType }
     *     
     */
    public void setMphantom(MphantomType value) {
        this.mphantom = value;
    }

    /**
     * Gets the value of the mfenced property.
     * 
     * @return
     *     possible object is
     *     {@link MfencedType }
     *     
     */
    public MfencedType getMfenced() {
        return mfenced;
    }

    /**
     * Sets the value of the mfenced property.
     * 
     * @param value
     *     allowed object is
     *     {@link MfencedType }
     *     
     */
    public void setMfenced(MfencedType value) {
        this.mfenced = value;
    }

    /**
     * Gets the value of the menclose property.
     * 
     * @return
     *     possible object is
     *     {@link MencloseType }
     *     
     */
    public MencloseType getMenclose() {
        return menclose;
    }

    /**
     * Sets the value of the menclose property.
     * 
     * @param value
     *     allowed object is
     *     {@link MencloseType }
     *     
     */
    public void setMenclose(MencloseType value) {
        this.menclose = value;
    }

    /**
     * Gets the value of the msub property.
     * 
     * @return
     *     possible object is
     *     {@link MsubType }
     *     
     */
    public MsubType getMsub() {
        return msub;
    }

    /**
     * Sets the value of the msub property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsubType }
     *     
     */
    public void setMsub(MsubType value) {
        this.msub = value;
    }

    /**
     * Gets the value of the msup property.
     * 
     * @return
     *     possible object is
     *     {@link MsupType }
     *     
     */
    public MsupType getMsup() {
        return msup;
    }

    /**
     * Sets the value of the msup property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsupType }
     *     
     */
    public void setMsup(MsupType value) {
        this.msup = value;
    }

    /**
     * Gets the value of the msubsup property.
     * 
     * @return
     *     possible object is
     *     {@link MsubsupType }
     *     
     */
    public MsubsupType getMsubsup() {
        return msubsup;
    }

    /**
     * Sets the value of the msubsup property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsubsupType }
     *     
     */
    public void setMsubsup(MsubsupType value) {
        this.msubsup = value;
    }

    /**
     * Gets the value of the munder property.
     * 
     * @return
     *     possible object is
     *     {@link MunderType }
     *     
     */
    public MunderType getMunder() {
        return munder;
    }

    /**
     * Sets the value of the munder property.
     * 
     * @param value
     *     allowed object is
     *     {@link MunderType }
     *     
     */
    public void setMunder(MunderType value) {
        this.munder = value;
    }

    /**
     * Gets the value of the mover property.
     * 
     * @return
     *     possible object is
     *     {@link MoverType }
     *     
     */
    public MoverType getMover() {
        return mover;
    }

    /**
     * Sets the value of the mover property.
     * 
     * @param value
     *     allowed object is
     *     {@link MoverType }
     *     
     */
    public void setMover(MoverType value) {
        this.mover = value;
    }

    /**
     * Gets the value of the munderover property.
     * 
     * @return
     *     possible object is
     *     {@link MunderoverType }
     *     
     */
    public MunderoverType getMunderover() {
        return munderover;
    }

    /**
     * Sets the value of the munderover property.
     * 
     * @param value
     *     allowed object is
     *     {@link MunderoverType }
     *     
     */
    public void setMunderover(MunderoverType value) {
        this.munderover = value;
    }

    /**
     * Gets the value of the mmultiscripts property.
     * 
     * @return
     *     possible object is
     *     {@link MmultiscriptsType }
     *     
     */
    public MmultiscriptsType getMmultiscripts() {
        return mmultiscripts;
    }

    /**
     * Sets the value of the mmultiscripts property.
     * 
     * @param value
     *     allowed object is
     *     {@link MmultiscriptsType }
     *     
     */
    public void setMmultiscripts(MmultiscriptsType value) {
        this.mmultiscripts = value;
    }

    /**
     * Gets the value of the mtable property.
     * 
     * @return
     *     possible object is
     *     {@link MtableType }
     *     
     */
    public MtableType getMtable() {
        return mtable;
    }

    /**
     * Sets the value of the mtable property.
     * 
     * @param value
     *     allowed object is
     *     {@link MtableType }
     *     
     */
    public void setMtable(MtableType value) {
        this.mtable = value;
    }

    /**
     * Gets the value of the maligngroup property.
     * 
     * @return
     *     possible object is
     *     {@link MaligngroupType }
     *     
     */
    public MaligngroupType getMaligngroup() {
        return maligngroup;
    }

    /**
     * Sets the value of the maligngroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link MaligngroupType }
     *     
     */
    public void setMaligngroup(MaligngroupType value) {
        this.maligngroup = value;
    }

    /**
     * Gets the value of the malignmark property.
     * 
     * @return
     *     possible object is
     *     {@link MalignmarkType }
     *     
     */
    public MalignmarkType getMalignmark() {
        return malignmark;
    }

    /**
     * Sets the value of the malignmark property.
     * 
     * @param value
     *     allowed object is
     *     {@link MalignmarkType }
     *     
     */
    public void setMalignmark(MalignmarkType value) {
        this.malignmark = value;
    }

    /**
     * Gets the value of the mspace property.
     * 
     * @return
     *     possible object is
     *     {@link MspaceType }
     *     
     */
    public MspaceType getMspace() {
        return mspace;
    }

    /**
     * Sets the value of the mspace property.
     * 
     * @param value
     *     allowed object is
     *     {@link MspaceType }
     *     
     */
    public void setMspace(MspaceType value) {
        this.mspace = value;
    }

    /**
     * Gets the value of the maction property.
     * 
     * @return
     *     possible object is
     *     {@link MactionType }
     *     
     */
    public MactionType getMaction() {
        return maction;
    }

    /**
     * Sets the value of the maction property.
     * 
     * @param value
     *     allowed object is
     *     {@link MactionType }
     *     
     */
    public void setMaction(MactionType value) {
        this.maction = value;
    }

    /**
     * Gets the value of the merror property.
     * 
     * @return
     *     possible object is
     *     {@link MerrorType }
     *     
     */
    public MerrorType getMerror() {
        return merror;
    }

    /**
     * Sets the value of the merror property.
     * 
     * @param value
     *     allowed object is
     *     {@link MerrorType }
     *     
     */
    public void setMerror(MerrorType value) {
        this.merror = value;
    }

    /**
     * Gets the value of the mstyle property.
     * 
     * @return
     *     possible object is
     *     {@link MstyleType }
     *     
     */
    public MstyleType getMstyle() {
        return mstyle;
    }

    /**
     * Sets the value of the mstyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link MstyleType }
     *     
     */
    public void setMstyle(MstyleType value) {
        this.mstyle = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the clazz property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClazz().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getClazz() {
        if (clazz == null) {
            clazz = new ArrayList<String>();
        }
        return this.clazz;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the style property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStyle() {
        return style;
    }

    /**
     * Sets the value of the style property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStyle(String value) {
        this.style = value;
    }

    /**
     * Gets the value of the xref property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getXref() {
        return xref;
    }

    /**
     * Sets the value of the xref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setXref(Object value) {
        this.xref = value;
    }

    /**
     * Gets the value of the href property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHref() {
        return href;
    }

    /**
     * Sets the value of the href property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHref(String value) {
        this.href = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
