//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.08.17 at 04:09:29 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.w3.org/1998/Math/MathML", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.flowcyt.facejava.transformation.jaxb;
