//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.08.17 at 04:09:29 PM PDT 
//


package org.flowcyt.facejava.transformation.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				The following pre-defined transformations are specified: linear, quadratic, natural logarithm, 
 * 				logarithm with a specified base (10 by default), hyperlog, bi-exponential, logicle, and split-scale.
 * 			
 * 
 * <p>Java class for Pre-defined complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Pre-defined">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="linear" type="{http://www.isac-net.org/std/Transformation-ML/v1.0/}Linear"/>
 *         &lt;element name="quadratic" type="{http://www.isac-net.org/std/Transformation-ML/v1.0/}Quadratic"/>
 *         &lt;element name="ln" type="{http://www.isac-net.org/std/Transformation-ML/v1.0/}Ln"/>
 *         &lt;element name="log" type="{http://www.isac-net.org/std/Transformation-ML/v1.0/}Log"/>
 *         &lt;element name="hyperlog" type="{http://www.isac-net.org/std/Transformation-ML/v1.0/}Hyperlog"/>
 *         &lt;element name="bi-exponential" type="{http://www.isac-net.org/std/Transformation-ML/v1.0/}Bi-exponential"/>
 *         &lt;element name="logicle" type="{http://www.isac-net.org/std/Transformation-ML/v1.0/}Logicle"/>
 *         &lt;element name="split-scale" type="{http://www.isac-net.org/std/Transformation-ML/v1.0/}Split-scale"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Pre-defined", namespace = "http://www.isac-net.org/std/Transformation-ML/v1.0/", propOrder = {
    "linear",
    "quadratic",
    "ln",
    "log",
    "hyperlog",
    "biExponential",
    "logicle",
    "splitScale"
})
public class PreDefined {

    @XmlElement(namespace = "http://www.isac-net.org/std/Transformation-ML/v1.0/")
    protected Linear linear;
    @XmlElement(namespace = "http://www.isac-net.org/std/Transformation-ML/v1.0/")
    protected Quadratic quadratic;
    @XmlElement(namespace = "http://www.isac-net.org/std/Transformation-ML/v1.0/")
    protected Ln ln;
    @XmlElement(namespace = "http://www.isac-net.org/std/Transformation-ML/v1.0/")
    protected Log log;
    @XmlElement(namespace = "http://www.isac-net.org/std/Transformation-ML/v1.0/")
    protected Hyperlog hyperlog;
    @XmlElement(name = "bi-exponential", namespace = "http://www.isac-net.org/std/Transformation-ML/v1.0/")
    protected BiExponential biExponential;
    @XmlElement(namespace = "http://www.isac-net.org/std/Transformation-ML/v1.0/")
    protected Logicle logicle;
    @XmlElement(name = "split-scale", namespace = "http://www.isac-net.org/std/Transformation-ML/v1.0/")
    protected SplitScale splitScale;

    /**
     * Gets the value of the linear property.
     * 
     * @return
     *     possible object is
     *     {@link Linear }
     *     
     */
    public Linear getLinear() {
        return linear;
    }

    /**
     * Sets the value of the linear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Linear }
     *     
     */
    public void setLinear(Linear value) {
        this.linear = value;
    }

    /**
     * Gets the value of the quadratic property.
     * 
     * @return
     *     possible object is
     *     {@link Quadratic }
     *     
     */
    public Quadratic getQuadratic() {
        return quadratic;
    }

    /**
     * Sets the value of the quadratic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quadratic }
     *     
     */
    public void setQuadratic(Quadratic value) {
        this.quadratic = value;
    }

    /**
     * Gets the value of the ln property.
     * 
     * @return
     *     possible object is
     *     {@link Ln }
     *     
     */
    public Ln getLn() {
        return ln;
    }

    /**
     * Sets the value of the ln property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ln }
     *     
     */
    public void setLn(Ln value) {
        this.ln = value;
    }

    /**
     * Gets the value of the log property.
     * 
     * @return
     *     possible object is
     *     {@link Log }
     *     
     */
    public Log getLog() {
        return log;
    }

    /**
     * Sets the value of the log property.
     * 
     * @param value
     *     allowed object is
     *     {@link Log }
     *     
     */
    public void setLog(Log value) {
        this.log = value;
    }

    /**
     * Gets the value of the hyperlog property.
     * 
     * @return
     *     possible object is
     *     {@link Hyperlog }
     *     
     */
    public Hyperlog getHyperlog() {
        return hyperlog;
    }

    /**
     * Sets the value of the hyperlog property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hyperlog }
     *     
     */
    public void setHyperlog(Hyperlog value) {
        this.hyperlog = value;
    }

    /**
     * Gets the value of the biExponential property.
     * 
     * @return
     *     possible object is
     *     {@link BiExponential }
     *     
     */
    public BiExponential getBiExponential() {
        return biExponential;
    }

    /**
     * Sets the value of the biExponential property.
     * 
     * @param value
     *     allowed object is
     *     {@link BiExponential }
     *     
     */
    public void setBiExponential(BiExponential value) {
        this.biExponential = value;
    }

    /**
     * Gets the value of the logicle property.
     * 
     * @return
     *     possible object is
     *     {@link Logicle }
     *     
     */
    public Logicle getLogicle() {
        return logicle;
    }

    /**
     * Sets the value of the logicle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Logicle }
     *     
     */
    public void setLogicle(Logicle value) {
        this.logicle = value;
    }

    /**
     * Gets the value of the splitScale property.
     * 
     * @return
     *     possible object is
     *     {@link SplitScale }
     *     
     */
    public SplitScale getSplitScale() {
        return splitScale;
    }

    /**
     * Sets the value of the splitScale property.
     * 
     * @param value
     *     allowed object is
     *     {@link SplitScale }
     *     
     */
    public void setSplitScale(SplitScale value) {
        this.splitScale = value;
    }

}
