//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.08.17 at 04:09:29 PM PDT 
//


package org.flowcyt.facejava.transformation.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				The type of the main Transformation-ML element.
 * 				
 * 				The transformation element may be used to create new parameters as transformation of 
 * 				original parameters from FCS files (or from other parameters that have been created by another 
 * 				transformation already). The transformation element prescribes the transformation 
 * 				and assigns a new name for the created parameter in order to enable its usage in further definition of gates.
 * 			
 * 
 * <p>Java class for Transformation-ML complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Transformation-ML">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="transformation" type="{http://www.isac-net.org/std/Transformation-ML/v1.0/}ParameterTransformation" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Transformation-ML", namespace = "http://www.isac-net.org/std/Transformation-ML/v1.0/", propOrder = {
    "transformation"
})
public class TransformationML {

    @XmlElement(namespace = "http://www.isac-net.org/std/Transformation-ML/v1.0/", required = true)
    protected List<ParameterTransformation> transformation;

    /**
     * Gets the value of the transformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParameterTransformation }
     * 
     * 
     */
    public List<ParameterTransformation> getTransformation() {
        if (transformation == null) {
            transformation = new ArrayList<ParameterTransformation>();
        }
        return this.transformation;
    }

}
