package:
  name: cytoflow
  version: {{ environ.get('CONDA_TAG', 'notag') }}

source:
  path: ../../..


build:
  number: {{ environ.get('CONDA_BUILD_NUMBER', '0') }}
  string: {{ environ.get('CONDA_BUILD_STRING', 'py35_none') }}
  entry_points:
    - cytoflow = cytoflowgui.run:run_gui
    - cf-channel_voltages = cytoflow.scripts.channel_voltages:main

requirements:
  build:
    - python==3.6.6
    - sphinx==1.7.7
    - numpy==1.15.0
    - pandas==0.23.4
    - bottleneck==1.2.1
    - numexpr==2.6.7
    - matplotlib==2.2.3
    - scipy==1.1.0
    - scikit-learn==0.19.1
    - traits==4.6.0
    - traitsui==6.0.0
    - pyface==6.0.0
    - envisage==4.6.0
    - nbformat==4.4.0
    - python-dateutil==2.7.3
    - statsmodels==0.9.0
    - pyqt==5.9.2
    - fcsparser==0.2.0
    - camel==0.1.2
    - yapf==0.22.0
    - seaborn==0.9.0
    - mock==2.0.0

  run:
    - python==3.6.6
    - numpy==1.15.0
    - pandas==0.23.4
    - bottleneck==1.2.1
    - numexpr==2.6.7
    - matplotlib==2.2.3
    - scipy==1.1.0
    - scikit-learn==0.19.1
    - traits==4.6.0
    - traitsui==6.0.0
    - pyface==6.0.0
    - envisage==4.6.0
    - nbformat==4.4.0
    - python-dateutil==2.7.3
    - statsmodels==0.9.0
    - pyqt==5.9.2
    - fcsparser==0.2.0
    - camel==0.1.2
    - yapf==0.22.0
    - seaborn==0.9.0


test:
  # Python imports
  imports:
    - cytoflow

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/bpteague/cytoflow
  license: GPLv2
  license_file: GPL.txt
  summary: 'Quantitative analyses for flow cytometry'

app:
    own_environment: True
    entry: cytoflow
    icon: icon.png

# See
# https://conda.io/docs/building/build.html for
# more information about meta.yaml
