package:
  name: cytoflow
  version: {{ environ.get('CONDA_TAG', 'notag') }}

source:
  path: ../../..


build:
  number: {{ environ.get('CONDA_BUILD_NUMBER', '0') }}
  string: {{ environ.get('CONDA_BUILD_STRING', 'py36_none') }}
  entry_points:
    - cytoflow = cytoflowgui.run:run_gui
    - cf-channel_voltages = cytoflow.scripts.channel_voltages:main

requirements:
  build:
    - python==3.6.10
    - numpy==1.18.1
    - pandas==1.0.3
    - matplotlib==3.1.3
    - bottleneck==1.3.2
    - numexpr==2.7.1
    - scipy==1.4.1
    - scikit-learn==0.22.1
    - seaborn==0.10.0
    - statsmodels==0.11.0

    - traits==6.0.0
    - traitsui==6.1.3
    - pyface==6.1.2
    - envisage==4.8.0
    - nbformat==5.0.4
    - python-dateutil==2.8.1

    - pyqt==5.9.2
    - qt==5.9.7
    - pyopengl==3.1.1a1

    - fcsparser==0.2.0
    - camel==0.1.2
    - yapf==0.22.0

    - mock==4.0.1
    - sphinx==2.4.4

  run:
    - python==3.6.10
    - numpy==1.18.1
    - pandas==1.0.3
    - matplotlib==3.1.3
    - bottleneck==1.3.2
    - numexpr==2.7.1
    - scipy==1.4.1
    - scikit-learn==0.22.1
    - seaborn==0.10.0
    - statsmodels==0.11.0

    - traits==6.0.0
    - traitsui==6.1.3
    - pyface==6.1.2
    - envisage==4.8.0
    - nbformat==5.0.4
    - python-dateutil==2.8.1
    
    - pyqt==5.9.2
    - qt==5.9.7
    - pyopengl==3.1.1a1
    
    - fcsparser==0.2.0
    - camel==0.1.2
    - yapf==0.22.0
    

    # make sure some compatible version of the jupyter notebook
    # gets installed
    - notebook


test:
  # Python imports
  imports:
    - cytoflow

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/bpteague/cytoflow
  license: GPLv2
  license_file: GPL.txt
  summary: 'Quantitative analyses for flow cytometry'

app:
    own_environment: True
    entry: cytoflow
    icon: icon.png

# See
# https://conda.io/docs/building/build.html for
# more information about meta.yaml
