package org.flowcyt.cfcs;
// CFCSData.java

/* ------------------------------------------------------------------------- *\
This software and documentation are provided 'as is' and Tree Star, Inc., its
contractors and partners specifically disclaim all other warranties, expressed
or implied, including but not limited to implied warranties of merchantability
and fitness for a particular purpose, or during any particular date range.

By using this software, you are agreeing to these limits of liability, and to
hold Tree Star harmless for any information, accurate or erroneous, that might
be generated by the program.  This software is intended for research use only.

Christopher Lane <cdl@best.classes> for Tree Star  1/14/2002      Copyright 2002
\* ------------------------------------------------------------------------- */


public interface CFCSData
{
    public static final int UNDEFINED = 0;
    public static final int LISTMODE = 1;
    public static final int CORRELATED = 2;
    public static final int UNCORRELATED = 3;

    public int getType();

    public byte[] getBytes();

    public void setBytes(byte[] bytes);
}
