//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.08.17 at 04:07:15 PM PDT 
//


package org.flowcyt.facejava.compensation.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Contains one or more compensation matrices.
 * 			
 * 
 * <p>Java class for Compensation-ML complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Compensation-ML">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="spilloverMatrix" type="{http://www.isac-net.org/std/Compensation-ML/v1.0/}SpilloverMatrix"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Compensation-ML", propOrder = {
    "spilloverMatrix"
})
public class CompensationML {

    @XmlElement(required = true)
    protected List<SpilloverMatrix> spilloverMatrix;

    /**
     * Gets the value of the spilloverMatrix property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the spilloverMatrix property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpilloverMatrix().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SpilloverMatrix }
     * 
     * 
     */
    public List<SpilloverMatrix> getSpilloverMatrix() {
        if (spilloverMatrix == null) {
            spilloverMatrix = new ArrayList<SpilloverMatrix>();
        }
        return this.spilloverMatrix;
    }

}
