//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.08.17 at 04:07:15 PM PDT 
//


package org.flowcyt.facejava.compensation.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.flowcyt.facejava.compensation.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CompensationML_QNAME = new QName("http://www.isac-net.org/std/Compensation-ML/v1.0/", "Compensation-ML");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.flowcyt.facejava.compensation.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SpilloverMatrix }
     * 
     */
    public SpilloverMatrix createSpilloverMatrix() {
        return new SpilloverMatrix();
    }

    /**
     * Create an instance of {@link Spillover }
     * 
     */
    public Spillover createSpillover() {
        return new Spillover();
    }

    /**
     * Create an instance of {@link Coefficient }
     * 
     */
    public Coefficient createCoefficient() {
        return new Coefficient();
    }

    /**
     * Create an instance of {@link CompensationML }
     * 
     */
    public CompensationML createCompensationML() {
        return new CompensationML();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompensationML }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.isac-net.org/std/Compensation-ML/v1.0/", name = "Compensation-ML")
    public JAXBElement<CompensationML> createCompensationML(CompensationML value) {
        return new JAXBElement<CompensationML>(_CompensationML_QNAME, CompensationML.class, null, value);
    }

}
