# (c) Massachusetts Institute of Technology 2015-2018
# (c) Brian Teague 2018-2022
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: Test and package on MacOS (Intel)
on: [push]
jobs:
      
  test-on-macos:
    name: Run nose2 on Intel MacOS runner
    runs-on: macos-15
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Check out repo
      uses: actions/checkout@v7.0.0
      with:
        submodules: true  
      
    - name: Remove lines with [win]
      run: |
        sed -i '' '/\[win\]/d' package/environment-build.yml
      
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v4.0.1
      with:
        auto-update-conda: true
        channels: defaults, cytoflow, conda-forge
        channel-priority: flexible
        activate-environment: cytoflow
        environment-file: package/environment-build.yml
    
    - name: Install package locally
      run: |
        pip install --verbose --editable .
        
    - name: Run cytoflow tests
      env:
        OMP_NUM_THREADS: 1
      run: |
        nose2 -v -c package/nose2.cfg cytoflow.tests

#     - name: Run cytoflowgui tests
#       env:
#         OMP_NUM_THREADS: 1
#       run: |
#         nose2 -v -c package/nose2.cfg cytoflowgui.tests -GUI        

    
  build-macos-conda-package:
    name: Build MacOS Intel conda package
    runs-on: macos-15
    needs: test-on-macos
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Check out repo
      uses: actions/checkout@v7.0.0
      with:
        fetch-depth: 0
        submodules: true
      
    - name: Remove lines with [win]
      run: |
        sed -i '' '/\[win\]/d' package/environment-build.yml
      
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v4.0.1
      with:
        auto-update-conda: true
        channels: defaults, cytoflow, conda-forge
        channel-priority: flexible
        activate-environment: cytoflow
        environment-file: package/environment-build.yml
        
    - name: Build conda package
#       continue-on-error: true
      run: |
        conda-render package/conda_recipes/cytoflow
        conda-build package/conda_recipes/cytoflow
        
#     - name: Zip up the build directory
#       run: |
#         zip -r conda-build.zip /Users/runner/miniconda3/envs/cytoflow/conda-bld/
#         
#     - name: Save the contents of the conda-build folder as artifacts
#       uses: actions/upload-artifact@v7.0.1
#       with:
#         name: macos-intel-conda-build-dir
#         retention-days: 7
#         path: conda-build.zip
        
    - name: Move conda package into the dist folder
      run: |
        mkdir dist
        mv `conda-build --output package/conda_recipes/cytoflow/` dist
        
    - name: Copy package/environment-build.yml into the dist folder
      run: |
        cp package/environment-build.yml dist/
        
    - name: List dist
      run: ls dist/
      
    - name: Save the contents of the dist/ folder as artifacts
      uses: actions/upload-artifact@v7.0.1
      with:
        name: macos-conda-package
        retention-days: 7
        path: dist/*
        
    - name: Get file names
      id: get_filenames
      run: |
        cd dist
        echo "CONDA_PACKAGE=$(ls cytoflow*.conda)" >> $GITHUB_OUTPUT
        
      # commented out because the file name is the same for each platform.
      # upload to anaconda.org instead.        
        
#     - name: Upload the conda package to the GitHub release
#       uses: actions/upload-release-asset@v1.0.2
#       env:
#         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
#       with:
#         upload_url: ${{ github.event.client_payload.release_url }} 
#         asset_path: dist/${{ steps.get_filenames.outputs.CONDA_PACKAGE }}
#         asset_name: ${{ steps.get_filenames.outputs.CONDA_PACKAGE }}
#         asset_content_type: application/zip
        
    - name: Upload conda package to anaconda.org
      if: github.ref_type == 'tag'
      run: |
<<<<<<< HEAD
<<<<<<< Upstream, based on 1.3.1-fixes
        anaconda -t ${{ secrets.CONDA_TOKEN }} upload --user cytoflow --force dist/${{ steps.get_filenames.outputs.CONDA_PACKAGE }}
=======
        anaconda -t ${{ secrets.CONDA_TOKEN }} upload --user cytoflow dist/${{ steps.get_filenames.outputs.CONDA_PACKAGE }}
>>>>>>> b386107 build: use softprops/action-gh-release
=======
        anaconda -t ${{ secrets.CONDA_TOKEN }} upload --user cytoflow dist/${{ steps.get_filenames.outputs.CONDA_PACKAGE }}
>>>>>>> branch 'master' of git@github.com:cytoflow/cytoflow.git


  build-macos-wheels:
    name: Build MacOS Intel wheels and binary extension
    needs: test-on-macos
    runs-on: macos-15
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Check out repo
      uses: actions/checkout@v7.0.0  
      with:
        fetch-depth: 0
        submodules: true
      
    - name: Remove lines with [win]
      run: |
        sed -i '' '/\[win\]/d' package/environment-build.yml
      
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v4.0.1
      with:
        auto-update-conda: true
        channels: defaults, cytoflow, conda-forge
        channel-priority: flexible
        activate-environment: cytoflow
        environment-file: package/environment-build.yml
        
    - name: Install packaging deps
      run: |
        pip install build
            
    - name: Install package locally
      run: |
        pip install --verbose --editable .
        
    - name: Build wheel
      run: |
        python -m build --wheel
        
    - name: Move C++ extensions into the dist folder
      run: |
        cp `find build | grep "\.so$"` dist/
        
    - name: List dist
      run: ls dist/
      
    - name: Save the contents of the dist/ folder as artifacts
      uses: actions/upload-artifact@v7.0.1
      with:
        name: macos-wheels
        retention-days: 7
        path: dist/*   
        
    - name: Get file names
      id: get_filenames
      run: |
        cd dist
        echo "EXTENSION_FILE=$(ls _Logicle*.so)" >> $GITHUB_OUTPUT
        echo "WHEEL_FILE=$(ls cytoflow*.whl)" >> $GITHUB_OUTPUT
        
    - name: Upload files to a Github release
      uses: softprops/action-gh-release@v3
      if: github.ref_type == 'tag'
      with:
        draft: true
<<<<<<< HEAD
<<<<<<< Upstream, based on 1.3.1-fixes
        working_directory: dist
=======
>>>>>>> b386107 build: use softprops/action-gh-release
=======
>>>>>>> branch 'master' of git@github.com:cytoflow/cytoflow.git
        files: |
          ${{ steps.get_filenames.outputs.EXTENSION_FILE }}
          ${{ steps.get_filenames.outputs.WHEEL_FILE }}
        
  build-macos-oneclick:
    name: Build MacOS Intel one-click
    needs: test-on-macos
    runs-on: macos-15
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Check out repo
      uses: actions/checkout@v7.0.0  
      with:
        fetch-depth: 0
        submodules: true
        
    - name: Query git tag
      id: tag
      run: echo "GIT_TAG=$(git describe --tags)" >> $GITHUB_ENV
        
    - name: Show Tag
      id: display
      run: |
        echo "Output from Find Tag: ${GIT_TAG}"
      
    - name: Remove lines with [win]
      run: |
        sed -i '' '/\[win\]/d' package/environment-build.yml
      
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v4.0.1
      with:
        auto-update-conda: true
        channels: defaults, cytoflow, conda-forge
        channel-priority: flexible
        activate-environment: cytoflow
        environment-file: package/environment-build.yml
            
    - name: Install package locally
      run: |
        pip install --verbose --editable .
        
    - name: Build embedded help docs
      run: |
        sphinx-build docs/user_manual/reference cytoflowgui/help
        
    - name: Build GUI binary
      run: |
        pyinstaller package/pyinstaller.spec
        
    - name: List dist
      run: ls dist/
        
    - name: Rename and zip Mac app
<<<<<<< HEAD
<<<<<<< Upstream, based on 1.3.1-fixes
      id: zip_app
=======
      id: zip_tarball
>>>>>>> b386107 build: use softprops/action-gh-release
=======
      id: zip_tarball
>>>>>>> branch 'master' of git@github.com:cytoflow/cytoflow.git
      run: |
        cd dist/
        mv Cytoflow.app Cytoflow-${GIT_TAG}.app
        zip -r cytoflow-gui-${GIT_TAG}-macos_x86-64.zip Cytoflow-${GIT_TAG}.app/
        rm -rf Cytoflow-${GIT_TAG}.app cytoflow
        echo "GUI_FILE=cytoflow-gui-${GIT_TAG}-macos_x86-64.zip" >> $GITHUB_OUTPUT
        
    - name: List dist
      run: ls dist/
      
    - name: Save the contents of the dist/ folder as artifacts
      uses: actions/upload-artifact@v7.0.1
      with:
        name: macos-oneclick
        retention-days: 7
        path: dist/*
        
    - name: Upload files to a Github release
      uses: softprops/action-gh-release@v3
      if: github.ref_type == 'tag'
      with:
        draft: true
<<<<<<< HEAD
<<<<<<< Upstream, based on 1.3.1-fixes
        working_directory: dist
        files: |
          ${{ steps.zip_app.outputs.GUI_FILE }}
=======
        files: |
          ${{ steps.rename_directory.outputs.GUI_FILE }}
>>>>>>> b386107 build: use softprops/action-gh-release
=======
        files: |
          ${{ steps.rename_directory.outputs.GUI_FILE }}
>>>>>>> branch 'master' of git@github.com:cytoflow/cytoflow.git
